<?php
/**
 * OfficialPageStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model\V3;
use \TencentAds\ObjectSerializer;

/**
 * OfficialPageStatus Class Doc Comment
 *
 * @category Class
 * @description 官方落地页状态
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OfficialPageStatus
{
    /**
     * Possible values of this enum
     */
    const EDITING = 'LANDING_PAGE_STATUS_EDITING';
    const PENDING = 'LANDING_PAGE_STATUS_PENDING';
    const APPROVED = 'LANDING_PAGE_STATUS_APPROVED';
    const REJECTED = 'LANDING_PAGE_STATUS_REJECTED';
    const OFFLINE = 'LANDING_PAGE_STATUS_OFFLINE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EDITING,
            self::PENDING,
            self::APPROVED,
            self::REJECTED,
            self::OFFLINE,
        ];
    }
}


