<?php
/**
 * SearchDynamicCreativesAddRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model\V3;

use \ArrayAccess;
use \TencentAds\ObjectSerializer;

/**
 * SearchDynamicCreativesAddRequest Class Doc Comment
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchDynamicCreativesAddRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SearchDynamicCreativesAddRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accountId' => 'int',
        'adgroupId' => 'int',
        'dynamicCreativeName' => 'string',
        'creativeTemplateId' => 'int',
        'deliveryMode' => '\TencentAds\Model\V3\DeliveryMode',
        'creativeComponents' => '\TencentAds\Model\V3\CreativeComponents',
        'searchIntelligentExtension' => '\TencentAds\Model\V3\ModelSwitch',
        'sublinkSwitch' => '\TencentAds\Model\V3\AdvertiserSublinkSwitch',
        'picMaterialSwitch' => '\TencentAds\Model\V3\AdvertiserPicMaterialSwitch'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accountId' => 'int64',
        'adgroupId' => 'int64',
        'dynamicCreativeName' => null,
        'creativeTemplateId' => 'int64',
        'deliveryMode' => null,
        'creativeComponents' => null,
        'searchIntelligentExtension' => null,
        'sublinkSwitch' => null,
        'picMaterialSwitch' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accountId' => 'account_id',
        'adgroupId' => 'adgroup_id',
        'dynamicCreativeName' => 'dynamic_creative_name',
        'creativeTemplateId' => 'creative_template_id',
        'deliveryMode' => 'delivery_mode',
        'creativeComponents' => 'creative_components',
        'searchIntelligentExtension' => 'search_intelligent_extension',
        'sublinkSwitch' => 'sublink_switch',
        'picMaterialSwitch' => 'pic_material_switch'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accountId' => 'setAccountId',
        'adgroupId' => 'setAdgroupId',
        'dynamicCreativeName' => 'setDynamicCreativeName',
        'creativeTemplateId' => 'setCreativeTemplateId',
        'deliveryMode' => 'setDeliveryMode',
        'creativeComponents' => 'setCreativeComponents',
        'searchIntelligentExtension' => 'setSearchIntelligentExtension',
        'sublinkSwitch' => 'setSublinkSwitch',
        'picMaterialSwitch' => 'setPicMaterialSwitch'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accountId' => 'getAccountId',
        'adgroupId' => 'getAdgroupId',
        'dynamicCreativeName' => 'getDynamicCreativeName',
        'creativeTemplateId' => 'getCreativeTemplateId',
        'deliveryMode' => 'getDeliveryMode',
        'creativeComponents' => 'getCreativeComponents',
        'searchIntelligentExtension' => 'getSearchIntelligentExtension',
        'sublinkSwitch' => 'getSublinkSwitch',
        'picMaterialSwitch' => 'getPicMaterialSwitch'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accountId'] = isset($data['accountId']) ? $data['accountId'] : null;
        $this->container['adgroupId'] = isset($data['adgroupId']) ? $data['adgroupId'] : null;
        $this->container['dynamicCreativeName'] = isset($data['dynamicCreativeName']) ? $data['dynamicCreativeName'] : null;
        $this->container['creativeTemplateId'] = isset($data['creativeTemplateId']) ? $data['creativeTemplateId'] : null;
        $this->container['deliveryMode'] = isset($data['deliveryMode']) ? $data['deliveryMode'] : null;
        $this->container['creativeComponents'] = isset($data['creativeComponents']) ? $data['creativeComponents'] : null;
        $this->container['searchIntelligentExtension'] = isset($data['searchIntelligentExtension']) ? $data['searchIntelligentExtension'] : null;
        $this->container['sublinkSwitch'] = isset($data['sublinkSwitch']) ? $data['sublinkSwitch'] : null;
        $this->container['picMaterialSwitch'] = isset($data['picMaterialSwitch']) ? $data['picMaterialSwitch'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accountId
     *
     * @return int|mixed
     */
    public function getAccountId()
    {
        return $this->container['accountId'];
    }

    /**
     * Sets accountId
     *
     * @param int|mixed $accountId accountId
     *
     * @return $this
     */
    public function setAccountId($accountId)
    {
        $this->container['accountId'] = $accountId;

        return $this;
    }

    /**
     * Gets adgroupId
     *
     * @return int|mixed
     */
    public function getAdgroupId()
    {
        return $this->container['adgroupId'];
    }

    /**
     * Sets adgroupId
     *
     * @param int|mixed $adgroupId adgroupId
     *
     * @return $this
     */
    public function setAdgroupId($adgroupId)
    {
        $this->container['adgroupId'] = $adgroupId;

        return $this;
    }

    /**
     * Gets dynamicCreativeName
     *
     * @return string|mixed
     */
    public function getDynamicCreativeName()
    {
        return $this->container['dynamicCreativeName'];
    }

    /**
     * Sets dynamicCreativeName
     *
     * @param string|mixed $dynamicCreativeName dynamicCreativeName
     *
     * @return $this
     */
    public function setDynamicCreativeName($dynamicCreativeName)
    {
        $this->container['dynamicCreativeName'] = $dynamicCreativeName;

        return $this;
    }

    /**
     * Gets creativeTemplateId
     *
     * @return int|mixed
     */
    public function getCreativeTemplateId()
    {
        return $this->container['creativeTemplateId'];
    }

    /**
     * Sets creativeTemplateId
     *
     * @param int|mixed $creativeTemplateId creativeTemplateId
     *
     * @return $this
     */
    public function setCreativeTemplateId($creativeTemplateId)
    {
        $this->container['creativeTemplateId'] = $creativeTemplateId;

        return $this;
    }

    /**
     * Gets deliveryMode
     *
     * @return \TencentAds\Model\V3\DeliveryMode|mixed
     */
    public function getDeliveryMode()
    {
        return $this->container['deliveryMode'];
    }

    /**
     * Sets deliveryMode
     *
     * @param \TencentAds\Model\V3\DeliveryMode|mixed $deliveryMode deliveryMode
     *
     * @return $this
     */
    public function setDeliveryMode($deliveryMode)
    {
        $this->container['deliveryMode'] = $deliveryMode;

        return $this;
    }

    /**
     * Gets creativeComponents
     *
     * @return \TencentAds\Model\V3\CreativeComponents|mixed
     */
    public function getCreativeComponents()
    {
        return $this->container['creativeComponents'];
    }

    /**
     * Sets creativeComponents
     *
     * @param \TencentAds\Model\V3\CreativeComponents|mixed $creativeComponents creativeComponents
     *
     * @return $this
     */
    public function setCreativeComponents($creativeComponents)
    {
        $this->container['creativeComponents'] = $creativeComponents;

        return $this;
    }

    /**
     * Gets searchIntelligentExtension
     *
     * @return \TencentAds\Model\V3\ModelSwitch|mixed
     */
    public function getSearchIntelligentExtension()
    {
        return $this->container['searchIntelligentExtension'];
    }

    /**
     * Sets searchIntelligentExtension
     *
     * @param \TencentAds\Model\V3\ModelSwitch|mixed $searchIntelligentExtension searchIntelligentExtension
     *
     * @return $this
     */
    public function setSearchIntelligentExtension($searchIntelligentExtension)
    {
        $this->container['searchIntelligentExtension'] = $searchIntelligentExtension;

        return $this;
    }

    /**
     * Gets sublinkSwitch
     *
     * @return \TencentAds\Model\V3\AdvertiserSublinkSwitch|mixed
     */
    public function getSublinkSwitch()
    {
        return $this->container['sublinkSwitch'];
    }

    /**
     * Sets sublinkSwitch
     *
     * @param \TencentAds\Model\V3\AdvertiserSublinkSwitch|mixed $sublinkSwitch sublinkSwitch
     *
     * @return $this
     */
    public function setSublinkSwitch($sublinkSwitch)
    {
        $this->container['sublinkSwitch'] = $sublinkSwitch;

        return $this;
    }

    /**
     * Gets picMaterialSwitch
     *
     * @return \TencentAds\Model\V3\AdvertiserPicMaterialSwitch|mixed
     */
    public function getPicMaterialSwitch()
    {
        return $this->container['picMaterialSwitch'];
    }

    /**
     * Sets picMaterialSwitch
     *
     * @param \TencentAds\Model\V3\AdvertiserPicMaterialSwitch|mixed $picMaterialSwitch picMaterialSwitch
     *
     * @return $this
     */
    public function setPicMaterialSwitch($picMaterialSwitch)
    {
        $this->container['picMaterialSwitch'] = $picMaterialSwitch;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


