<?php
/**
 * AdPowerPreviewViewerIdType
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;
use \TencentAds\ObjectSerializer;

/**
 * AdPowerPreviewViewerIdType Class Doc Comment
 *
 * @category Class
 * @description 受众id类型
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdPowerPreviewViewerIdType
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'UNKNOWN';
    const USER_ID_TYPE_QQ_ID = 'USER_ID_TYPE_QQ_ID';
    const USER_ID_TYPE_WECHAT_ID = 'USER_ID_TYPE_WECHAT_ID';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::USER_ID_TYPE_QQ_ID,
            self::USER_ID_TYPE_WECHAT_ID,
        ];
    }
}


