<?php
/**
 * AdvertiserCustomerSystemStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;
use \TencentAds\ObjectSerializer;

/**
 * AdvertiserCustomerSystemStatus Class Doc Comment
 *
 * @category Class
 * @description 客户系统状态，详见 &lt;a href&#x3D;&#39;api_customer_system_status&#39; target&#x3D;&#39;_blank&#39;&gt;[客户系统状态]&lt;/a&gt;
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdvertiserCustomerSystemStatus
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'UNKNOWN';
    const CUSTOMER_STATUS_NORMAL = 'CUSTOMER_STATUS_NORMAL';
    const CUSTOMER_STATUS_PENDING = 'CUSTOMER_STATUS_PENDING';
    const CUSTOMER_STATUS_DENIED = 'CUSTOMER_STATUS_DENIED';
    const CUSTOMER_STATUS_FROZEN = 'CUSTOMER_STATUS_FROZEN';
    const CUSTOMER_STATUS_TOBE_ACCEPTED = 'CUSTOMER_STATUS_TOBE_ACCEPTED';
    const CUSTOMER_STATUS_TOBE_ACTIVATED = 'CUSTOMER_STATUS_TOBE_ACTIVATED';
    const CUSTOMER_STATUS_SUSPEND = 'CUSTOMER_STATUS_SUSPEND';
    const CUSTOMER_STATUS_MATERIAL_PREPARED = 'CUSTOMER_STATUS_MATERIAL_PREPARED';
    const CUSTOMER_STATUS_DELETED = 'CUSTOMER_STATUS_DELETED';
    const CUSTOMER_STATUS_FROZEN_TEMPORARILY = 'CUSTOMER_STATUS_FROZEN_TEMPORARILY';
    const CUSTOMER_STATUS_UNREGISTERED = 'CUSTOMER_STATUS_UNREGISTERED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::CUSTOMER_STATUS_NORMAL,
            self::CUSTOMER_STATUS_PENDING,
            self::CUSTOMER_STATUS_DENIED,
            self::CUSTOMER_STATUS_FROZEN,
            self::CUSTOMER_STATUS_TOBE_ACCEPTED,
            self::CUSTOMER_STATUS_TOBE_ACTIVATED,
            self::CUSTOMER_STATUS_SUSPEND,
            self::CUSTOMER_STATUS_MATERIAL_PREPARED,
            self::CUSTOMER_STATUS_DELETED,
            self::CUSTOMER_STATUS_FROZEN_TEMPORARILY,
            self::CUSTOMER_STATUS_UNREGISTERED,
        ];
    }
}


