<?php
/**
 * AdvertiserGetListStruct
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;

use \ArrayAccess;
use \TencentAds\ObjectSerializer;

/**
 * AdvertiserGetListStruct Class Doc Comment
 *
 * @category Class
 * @description 返回结构
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdvertiserGetListStruct implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AdvertiserGetListStruct';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accountId' => 'int',
        'dailyBudget' => 'int',
        'systemStatus' => '\TencentAds\Model\CustomerSystemStatus',
        'rejectMessage' => 'string',
        'corporationName' => 'string',
        'corporationLicence' => 'string',
        'certificationImageId' => 'string',
        'certificationImage' => 'string',
        'identityNumber' => 'string',
        'individualQualification' => '\TencentAds\Model\IndividualQualificationRead',
        'corporateImageName' => 'string',
        'corporateImageLogo' => 'string',
        'systemIndustryId' => 'int',
        'customizedIndustry' => 'string',
        'introductionUrl' => 'string',
        'corporateBrandName' => 'string',
        'industryQualificationImageIdList' => 'string[]',
        'industryQualificationImage' => 'string[]',
        'adQualificationImageIdList' => 'string[]',
        'adQualificationImage' => 'string[]',
        'contactPerson' => 'string',
        'contactPersonEmail' => 'string',
        'contactPersonTelephone' => 'string',
        'contactPersonMobile' => 'string',
        'websites' => '\TencentAds\Model\WebsiteReadStruct[]',
        'mdmId' => 'int',
        'mdmName' => 'string',
        'agencyAccountId' => 'int',
        'operators' => '\TencentAds\Model\AdvertiserOperatorStruct[]',
        'memo' => 'string',
        'areaCode' => 'int',
        'isLocalBusiness' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accountId' => 'int64',
        'dailyBudget' => 'int64',
        'systemStatus' => null,
        'rejectMessage' => null,
        'corporationName' => null,
        'corporationLicence' => null,
        'certificationImageId' => null,
        'certificationImage' => null,
        'identityNumber' => null,
        'individualQualification' => null,
        'corporateImageName' => null,
        'corporateImageLogo' => null,
        'systemIndustryId' => 'int64',
        'customizedIndustry' => null,
        'introductionUrl' => null,
        'corporateBrandName' => null,
        'industryQualificationImageIdList' => null,
        'industryQualificationImage' => null,
        'adQualificationImageIdList' => null,
        'adQualificationImage' => null,
        'contactPerson' => null,
        'contactPersonEmail' => null,
        'contactPersonTelephone' => null,
        'contactPersonMobile' => null,
        'websites' => null,
        'mdmId' => 'int64',
        'mdmName' => null,
        'agencyAccountId' => 'int64',
        'operators' => null,
        'memo' => null,
        'areaCode' => 'int64',
        'isLocalBusiness' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accountId' => 'account_id',
        'dailyBudget' => 'daily_budget',
        'systemStatus' => 'system_status',
        'rejectMessage' => 'reject_message',
        'corporationName' => 'corporation_name',
        'corporationLicence' => 'corporation_licence',
        'certificationImageId' => 'certification_image_id',
        'certificationImage' => 'certification_image',
        'identityNumber' => 'identity_number',
        'individualQualification' => 'individual_qualification',
        'corporateImageName' => 'corporate_image_name',
        'corporateImageLogo' => 'corporate_image_logo',
        'systemIndustryId' => 'system_industry_id',
        'customizedIndustry' => 'customized_industry',
        'introductionUrl' => 'introduction_url',
        'corporateBrandName' => 'corporate_brand_name',
        'industryQualificationImageIdList' => 'industry_qualification_image_id_list',
        'industryQualificationImage' => 'industry_qualification_image',
        'adQualificationImageIdList' => 'ad_qualification_image_id_list',
        'adQualificationImage' => 'ad_qualification_image',
        'contactPerson' => 'contact_person',
        'contactPersonEmail' => 'contact_person_email',
        'contactPersonTelephone' => 'contact_person_telephone',
        'contactPersonMobile' => 'contact_person_mobile',
        'websites' => 'websites',
        'mdmId' => 'mdm_id',
        'mdmName' => 'mdm_name',
        'agencyAccountId' => 'agency_account_id',
        'operators' => 'operators',
        'memo' => 'memo',
        'areaCode' => 'area_code',
        'isLocalBusiness' => 'is_local_business'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accountId' => 'setAccountId',
        'dailyBudget' => 'setDailyBudget',
        'systemStatus' => 'setSystemStatus',
        'rejectMessage' => 'setRejectMessage',
        'corporationName' => 'setCorporationName',
        'corporationLicence' => 'setCorporationLicence',
        'certificationImageId' => 'setCertificationImageId',
        'certificationImage' => 'setCertificationImage',
        'identityNumber' => 'setIdentityNumber',
        'individualQualification' => 'setIndividualQualification',
        'corporateImageName' => 'setCorporateImageName',
        'corporateImageLogo' => 'setCorporateImageLogo',
        'systemIndustryId' => 'setSystemIndustryId',
        'customizedIndustry' => 'setCustomizedIndustry',
        'introductionUrl' => 'setIntroductionUrl',
        'corporateBrandName' => 'setCorporateBrandName',
        'industryQualificationImageIdList' => 'setIndustryQualificationImageIdList',
        'industryQualificationImage' => 'setIndustryQualificationImage',
        'adQualificationImageIdList' => 'setAdQualificationImageIdList',
        'adQualificationImage' => 'setAdQualificationImage',
        'contactPerson' => 'setContactPerson',
        'contactPersonEmail' => 'setContactPersonEmail',
        'contactPersonTelephone' => 'setContactPersonTelephone',
        'contactPersonMobile' => 'setContactPersonMobile',
        'websites' => 'setWebsites',
        'mdmId' => 'setMdmId',
        'mdmName' => 'setMdmName',
        'agencyAccountId' => 'setAgencyAccountId',
        'operators' => 'setOperators',
        'memo' => 'setMemo',
        'areaCode' => 'setAreaCode',
        'isLocalBusiness' => 'setIsLocalBusiness'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accountId' => 'getAccountId',
        'dailyBudget' => 'getDailyBudget',
        'systemStatus' => 'getSystemStatus',
        'rejectMessage' => 'getRejectMessage',
        'corporationName' => 'getCorporationName',
        'corporationLicence' => 'getCorporationLicence',
        'certificationImageId' => 'getCertificationImageId',
        'certificationImage' => 'getCertificationImage',
        'identityNumber' => 'getIdentityNumber',
        'individualQualification' => 'getIndividualQualification',
        'corporateImageName' => 'getCorporateImageName',
        'corporateImageLogo' => 'getCorporateImageLogo',
        'systemIndustryId' => 'getSystemIndustryId',
        'customizedIndustry' => 'getCustomizedIndustry',
        'introductionUrl' => 'getIntroductionUrl',
        'corporateBrandName' => 'getCorporateBrandName',
        'industryQualificationImageIdList' => 'getIndustryQualificationImageIdList',
        'industryQualificationImage' => 'getIndustryQualificationImage',
        'adQualificationImageIdList' => 'getAdQualificationImageIdList',
        'adQualificationImage' => 'getAdQualificationImage',
        'contactPerson' => 'getContactPerson',
        'contactPersonEmail' => 'getContactPersonEmail',
        'contactPersonTelephone' => 'getContactPersonTelephone',
        'contactPersonMobile' => 'getContactPersonMobile',
        'websites' => 'getWebsites',
        'mdmId' => 'getMdmId',
        'mdmName' => 'getMdmName',
        'agencyAccountId' => 'getAgencyAccountId',
        'operators' => 'getOperators',
        'memo' => 'getMemo',
        'areaCode' => 'getAreaCode',
        'isLocalBusiness' => 'getIsLocalBusiness'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accountId'] = isset($data['accountId']) ? $data['accountId'] : null;
        $this->container['dailyBudget'] = isset($data['dailyBudget']) ? $data['dailyBudget'] : null;
        $this->container['systemStatus'] = isset($data['systemStatus']) ? $data['systemStatus'] : null;
        $this->container['rejectMessage'] = isset($data['rejectMessage']) ? $data['rejectMessage'] : null;
        $this->container['corporationName'] = isset($data['corporationName']) ? $data['corporationName'] : null;
        $this->container['corporationLicence'] = isset($data['corporationLicence']) ? $data['corporationLicence'] : null;
        $this->container['certificationImageId'] = isset($data['certificationImageId']) ? $data['certificationImageId'] : null;
        $this->container['certificationImage'] = isset($data['certificationImage']) ? $data['certificationImage'] : null;
        $this->container['identityNumber'] = isset($data['identityNumber']) ? $data['identityNumber'] : null;
        $this->container['individualQualification'] = isset($data['individualQualification']) ? $data['individualQualification'] : null;
        $this->container['corporateImageName'] = isset($data['corporateImageName']) ? $data['corporateImageName'] : null;
        $this->container['corporateImageLogo'] = isset($data['corporateImageLogo']) ? $data['corporateImageLogo'] : null;
        $this->container['systemIndustryId'] = isset($data['systemIndustryId']) ? $data['systemIndustryId'] : null;
        $this->container['customizedIndustry'] = isset($data['customizedIndustry']) ? $data['customizedIndustry'] : null;
        $this->container['introductionUrl'] = isset($data['introductionUrl']) ? $data['introductionUrl'] : null;
        $this->container['corporateBrandName'] = isset($data['corporateBrandName']) ? $data['corporateBrandName'] : null;
        $this->container['industryQualificationImageIdList'] = isset($data['industryQualificationImageIdList']) ? $data['industryQualificationImageIdList'] : null;
        $this->container['industryQualificationImage'] = isset($data['industryQualificationImage']) ? $data['industryQualificationImage'] : null;
        $this->container['adQualificationImageIdList'] = isset($data['adQualificationImageIdList']) ? $data['adQualificationImageIdList'] : null;
        $this->container['adQualificationImage'] = isset($data['adQualificationImage']) ? $data['adQualificationImage'] : null;
        $this->container['contactPerson'] = isset($data['contactPerson']) ? $data['contactPerson'] : null;
        $this->container['contactPersonEmail'] = isset($data['contactPersonEmail']) ? $data['contactPersonEmail'] : null;
        $this->container['contactPersonTelephone'] = isset($data['contactPersonTelephone']) ? $data['contactPersonTelephone'] : null;
        $this->container['contactPersonMobile'] = isset($data['contactPersonMobile']) ? $data['contactPersonMobile'] : null;
        $this->container['websites'] = isset($data['websites']) ? $data['websites'] : null;
        $this->container['mdmId'] = isset($data['mdmId']) ? $data['mdmId'] : null;
        $this->container['mdmName'] = isset($data['mdmName']) ? $data['mdmName'] : null;
        $this->container['agencyAccountId'] = isset($data['agencyAccountId']) ? $data['agencyAccountId'] : null;
        $this->container['operators'] = isset($data['operators']) ? $data['operators'] : null;
        $this->container['memo'] = isset($data['memo']) ? $data['memo'] : null;
        $this->container['areaCode'] = isset($data['areaCode']) ? $data['areaCode'] : null;
        $this->container['isLocalBusiness'] = isset($data['isLocalBusiness']) ? $data['isLocalBusiness'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accountId
     *
     * @return int|mixed
     */
    public function getAccountId()
    {
        return $this->container['accountId'];
    }

    /**
     * Sets accountId
     *
     * @param int|mixed $accountId accountId
     *
     * @return $this
     */
    public function setAccountId($accountId)
    {
        $this->container['accountId'] = $accountId;

        return $this;
    }

    /**
     * Gets dailyBudget
     *
     * @return int|mixed
     */
    public function getDailyBudget()
    {
        return $this->container['dailyBudget'];
    }

    /**
     * Sets dailyBudget
     *
     * @param int|mixed $dailyBudget dailyBudget
     *
     * @return $this
     */
    public function setDailyBudget($dailyBudget)
    {
        $this->container['dailyBudget'] = $dailyBudget;

        return $this;
    }

    /**
     * Gets systemStatus
     *
     * @return \TencentAds\Model\CustomerSystemStatus|mixed
     */
    public function getSystemStatus()
    {
        return $this->container['systemStatus'];
    }

    /**
     * Sets systemStatus
     *
     * @param \TencentAds\Model\CustomerSystemStatus|mixed $systemStatus systemStatus
     *
     * @return $this
     */
    public function setSystemStatus($systemStatus)
    {
        $this->container['systemStatus'] = $systemStatus;

        return $this;
    }

    /**
     * Gets rejectMessage
     *
     * @return string|mixed
     */
    public function getRejectMessage()
    {
        return $this->container['rejectMessage'];
    }

    /**
     * Sets rejectMessage
     *
     * @param string|mixed $rejectMessage rejectMessage
     *
     * @return $this
     */
    public function setRejectMessage($rejectMessage)
    {
        $this->container['rejectMessage'] = $rejectMessage;

        return $this;
    }

    /**
     * Gets corporationName
     *
     * @return string|mixed
     */
    public function getCorporationName()
    {
        return $this->container['corporationName'];
    }

    /**
     * Sets corporationName
     *
     * @param string|mixed $corporationName corporationName
     *
     * @return $this
     */
    public function setCorporationName($corporationName)
    {
        $this->container['corporationName'] = $corporationName;

        return $this;
    }

    /**
     * Gets corporationLicence
     *
     * @return string|mixed
     */
    public function getCorporationLicence()
    {
        return $this->container['corporationLicence'];
    }

    /**
     * Sets corporationLicence
     *
     * @param string|mixed $corporationLicence corporationLicence
     *
     * @return $this
     */
    public function setCorporationLicence($corporationLicence)
    {
        $this->container['corporationLicence'] = $corporationLicence;

        return $this;
    }

    /**
     * Gets certificationImageId
     *
     * @return string|mixed
     */
    public function getCertificationImageId()
    {
        return $this->container['certificationImageId'];
    }

    /**
     * Sets certificationImageId
     *
     * @param string|mixed $certificationImageId certificationImageId
     *
     * @return $this
     */
    public function setCertificationImageId($certificationImageId)
    {
        $this->container['certificationImageId'] = $certificationImageId;

        return $this;
    }

    /**
     * Gets certificationImage
     *
     * @return string|mixed
     */
    public function getCertificationImage()
    {
        return $this->container['certificationImage'];
    }

    /**
     * Sets certificationImage
     *
     * @param string|mixed $certificationImage certificationImage
     *
     * @return $this
     */
    public function setCertificationImage($certificationImage)
    {
        $this->container['certificationImage'] = $certificationImage;

        return $this;
    }

    /**
     * Gets identityNumber
     *
     * @return string|mixed
     */
    public function getIdentityNumber()
    {
        return $this->container['identityNumber'];
    }

    /**
     * Sets identityNumber
     *
     * @param string|mixed $identityNumber identityNumber
     *
     * @return $this
     */
    public function setIdentityNumber($identityNumber)
    {
        $this->container['identityNumber'] = $identityNumber;

        return $this;
    }

    /**
     * Gets individualQualification
     *
     * @return \TencentAds\Model\IndividualQualificationRead|mixed
     */
    public function getIndividualQualification()
    {
        return $this->container['individualQualification'];
    }

    /**
     * Sets individualQualification
     *
     * @param \TencentAds\Model\IndividualQualificationRead|mixed $individualQualification individualQualification
     *
     * @return $this
     */
    public function setIndividualQualification($individualQualification)
    {
        $this->container['individualQualification'] = $individualQualification;

        return $this;
    }

    /**
     * Gets corporateImageName
     *
     * @return string|mixed
     */
    public function getCorporateImageName()
    {
        return $this->container['corporateImageName'];
    }

    /**
     * Sets corporateImageName
     *
     * @param string|mixed $corporateImageName corporateImageName
     *
     * @return $this
     */
    public function setCorporateImageName($corporateImageName)
    {
        $this->container['corporateImageName'] = $corporateImageName;

        return $this;
    }

    /**
     * Gets corporateImageLogo
     *
     * @return string|mixed
     */
    public function getCorporateImageLogo()
    {
        return $this->container['corporateImageLogo'];
    }

    /**
     * Sets corporateImageLogo
     *
     * @param string|mixed $corporateImageLogo corporateImageLogo
     *
     * @return $this
     */
    public function setCorporateImageLogo($corporateImageLogo)
    {
        $this->container['corporateImageLogo'] = $corporateImageLogo;

        return $this;
    }

    /**
     * Gets systemIndustryId
     *
     * @return int|mixed
     */
    public function getSystemIndustryId()
    {
        return $this->container['systemIndustryId'];
    }

    /**
     * Sets systemIndustryId
     *
     * @param int|mixed $systemIndustryId systemIndustryId
     *
     * @return $this
     */
    public function setSystemIndustryId($systemIndustryId)
    {
        $this->container['systemIndustryId'] = $systemIndustryId;

        return $this;
    }

    /**
     * Gets customizedIndustry
     *
     * @return string|mixed
     */
    public function getCustomizedIndustry()
    {
        return $this->container['customizedIndustry'];
    }

    /**
     * Sets customizedIndustry
     *
     * @param string|mixed $customizedIndustry customizedIndustry
     *
     * @return $this
     */
    public function setCustomizedIndustry($customizedIndustry)
    {
        $this->container['customizedIndustry'] = $customizedIndustry;

        return $this;
    }

    /**
     * Gets introductionUrl
     *
     * @return string|mixed
     */
    public function getIntroductionUrl()
    {
        return $this->container['introductionUrl'];
    }

    /**
     * Sets introductionUrl
     *
     * @param string|mixed $introductionUrl introductionUrl
     *
     * @return $this
     */
    public function setIntroductionUrl($introductionUrl)
    {
        $this->container['introductionUrl'] = $introductionUrl;

        return $this;
    }

    /**
     * Gets corporateBrandName
     *
     * @return string|mixed
     */
    public function getCorporateBrandName()
    {
        return $this->container['corporateBrandName'];
    }

    /**
     * Sets corporateBrandName
     *
     * @param string|mixed $corporateBrandName corporateBrandName
     *
     * @return $this
     */
    public function setCorporateBrandName($corporateBrandName)
    {
        $this->container['corporateBrandName'] = $corporateBrandName;

        return $this;
    }

    /**
     * Gets industryQualificationImageIdList
     *
     * @return string[]|mixed
     */
    public function getIndustryQualificationImageIdList()
    {
        return $this->container['industryQualificationImageIdList'];
    }

    /**
     * Sets industryQualificationImageIdList
     *
     * @param string[]|mixed $industryQualificationImageIdList industryQualificationImageIdList
     *
     * @return $this
     */
    public function setIndustryQualificationImageIdList($industryQualificationImageIdList)
    {
        $this->container['industryQualificationImageIdList'] = $industryQualificationImageIdList;

        return $this;
    }

    /**
     * Gets industryQualificationImage
     *
     * @return string[]|mixed
     */
    public function getIndustryQualificationImage()
    {
        return $this->container['industryQualificationImage'];
    }

    /**
     * Sets industryQualificationImage
     *
     * @param string[]|mixed $industryQualificationImage industryQualificationImage
     *
     * @return $this
     */
    public function setIndustryQualificationImage($industryQualificationImage)
    {
        $this->container['industryQualificationImage'] = $industryQualificationImage;

        return $this;
    }

    /**
     * Gets adQualificationImageIdList
     *
     * @return string[]|mixed
     */
    public function getAdQualificationImageIdList()
    {
        return $this->container['adQualificationImageIdList'];
    }

    /**
     * Sets adQualificationImageIdList
     *
     * @param string[]|mixed $adQualificationImageIdList adQualificationImageIdList
     *
     * @return $this
     */
    public function setAdQualificationImageIdList($adQualificationImageIdList)
    {
        $this->container['adQualificationImageIdList'] = $adQualificationImageIdList;

        return $this;
    }

    /**
     * Gets adQualificationImage
     *
     * @return string[]|mixed
     */
    public function getAdQualificationImage()
    {
        return $this->container['adQualificationImage'];
    }

    /**
     * Sets adQualificationImage
     *
     * @param string[]|mixed $adQualificationImage adQualificationImage
     *
     * @return $this
     */
    public function setAdQualificationImage($adQualificationImage)
    {
        $this->container['adQualificationImage'] = $adQualificationImage;

        return $this;
    }

    /**
     * Gets contactPerson
     *
     * @return string|mixed
     */
    public function getContactPerson()
    {
        return $this->container['contactPerson'];
    }

    /**
     * Sets contactPerson
     *
     * @param string|mixed $contactPerson contactPerson
     *
     * @return $this
     */
    public function setContactPerson($contactPerson)
    {
        $this->container['contactPerson'] = $contactPerson;

        return $this;
    }

    /**
     * Gets contactPersonEmail
     *
     * @return string|mixed
     */
    public function getContactPersonEmail()
    {
        return $this->container['contactPersonEmail'];
    }

    /**
     * Sets contactPersonEmail
     *
     * @param string|mixed $contactPersonEmail contactPersonEmail
     *
     * @return $this
     */
    public function setContactPersonEmail($contactPersonEmail)
    {
        $this->container['contactPersonEmail'] = $contactPersonEmail;

        return $this;
    }

    /**
     * Gets contactPersonTelephone
     *
     * @return string|mixed
     */
    public function getContactPersonTelephone()
    {
        return $this->container['contactPersonTelephone'];
    }

    /**
     * Sets contactPersonTelephone
     *
     * @param string|mixed $contactPersonTelephone contactPersonTelephone
     *
     * @return $this
     */
    public function setContactPersonTelephone($contactPersonTelephone)
    {
        $this->container['contactPersonTelephone'] = $contactPersonTelephone;

        return $this;
    }

    /**
     * Gets contactPersonMobile
     *
     * @return string|mixed
     */
    public function getContactPersonMobile()
    {
        return $this->container['contactPersonMobile'];
    }

    /**
     * Sets contactPersonMobile
     *
     * @param string|mixed $contactPersonMobile contactPersonMobile
     *
     * @return $this
     */
    public function setContactPersonMobile($contactPersonMobile)
    {
        $this->container['contactPersonMobile'] = $contactPersonMobile;

        return $this;
    }

    /**
     * Gets websites
     *
     * @return \TencentAds\Model\WebsiteReadStruct[]|mixed
     */
    public function getWebsites()
    {
        return $this->container['websites'];
    }

    /**
     * Sets websites
     *
     * @param \TencentAds\Model\WebsiteReadStruct[]|mixed $websites websites
     *
     * @return $this
     */
    public function setWebsites($websites)
    {
        $this->container['websites'] = $websites;

        return $this;
    }

    /**
     * Gets mdmId
     *
     * @return int|mixed
     */
    public function getMdmId()
    {
        return $this->container['mdmId'];
    }

    /**
     * Sets mdmId
     *
     * @param int|mixed $mdmId mdmId
     *
     * @return $this
     */
    public function setMdmId($mdmId)
    {
        $this->container['mdmId'] = $mdmId;

        return $this;
    }

    /**
     * Gets mdmName
     *
     * @return string|mixed
     */
    public function getMdmName()
    {
        return $this->container['mdmName'];
    }

    /**
     * Sets mdmName
     *
     * @param string|mixed $mdmName mdmName
     *
     * @return $this
     */
    public function setMdmName($mdmName)
    {
        $this->container['mdmName'] = $mdmName;

        return $this;
    }

    /**
     * Gets agencyAccountId
     *
     * @return int|mixed
     */
    public function getAgencyAccountId()
    {
        return $this->container['agencyAccountId'];
    }

    /**
     * Sets agencyAccountId
     *
     * @param int|mixed $agencyAccountId agencyAccountId
     *
     * @return $this
     */
    public function setAgencyAccountId($agencyAccountId)
    {
        $this->container['agencyAccountId'] = $agencyAccountId;

        return $this;
    }

    /**
     * Gets operators
     *
     * @return \TencentAds\Model\AdvertiserOperatorStruct[]|mixed
     */
    public function getOperators()
    {
        return $this->container['operators'];
    }

    /**
     * Sets operators
     *
     * @param \TencentAds\Model\AdvertiserOperatorStruct[]|mixed $operators operators
     *
     * @return $this
     */
    public function setOperators($operators)
    {
        $this->container['operators'] = $operators;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string|mixed
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string|mixed $memo memo
     *
     * @return $this
     */
    public function setMemo($memo)
    {
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets areaCode
     *
     * @return int|mixed
     */
    public function getAreaCode()
    {
        return $this->container['areaCode'];
    }

    /**
     * Sets areaCode
     *
     * @param int|mixed $areaCode areaCode
     *
     * @return $this
     */
    public function setAreaCode($areaCode)
    {
        $this->container['areaCode'] = $areaCode;

        return $this;
    }

    /**
     * Gets isLocalBusiness
     *
     * @return bool|mixed
     */
    public function getIsLocalBusiness()
    {
        return $this->container['isLocalBusiness'];
    }

    /**
     * Sets isLocalBusiness
     *
     * @param bool|mixed $isLocalBusiness isLocalBusiness
     *
     * @return $this
     */
    public function setIsLocalBusiness($isLocalBusiness)
    {
        $this->container['isLocalBusiness'] = $isLocalBusiness;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


