<?php
/**
 * AutoAcquisitionStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;
use \TencentAds\ObjectSerializer;

/**
 * AutoAcquisitionStatus Class Doc Comment
 *
 * @category Class
 * @description 一键起量状态
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AutoAcquisitionStatus
{
    /**
     * Possible values of this enum
     */
    const ACQUISTION_STATUS_UNKNOW = 'AUTO_ACQUISTION_STATUS_UNKNOW';
    const ACQUISTION_STATUS_PENDING = 'AUTO_ACQUISTION_STATUS_PENDING';
    const ACQUISTION_STATUS_END_LESS_THAN_24_H = 'AUTO_ACQUISTION_STATUS_END_LESS_THAN_24H';
    const ACQUISTION_STATUS_END_MORE_THAN_24_H = 'AUTO_ACQUISTION_STATUS_END_MORE_THAN_24H';
    const ACQUISTION_STATUS_COMPLETED = 'AUTO_ACQUISTION_STATUS_COMPLETED';
    const ACQUISTION_STATUS_SUSPEND_ON_LEARNING_FAIL = 'AUTO_ACQUISTION_STATUS_SUSPEND_ON_LEARNING_FAIL';
    const ACQUISTION_STATUS_SUSPEND_ON_PLAYING_FAIL = 'AUTO_ACQUISTION_STATUS_SUSPEND_ON_PLAYING_FAIL';
    const ACQUISTION_STATUS_ADVERTISER_CLOSED = 'AUTO_ACQUISTION_STATUS_ADVERTISER_CLOSED';
    const ACQUISITION_STATUS_PENDING = 'AUTO_ACQUISITION_STATUS_PENDING';
    const ACQUISITION_STATUS_COMPLETED = 'AUTO_ACQUISITION_STATUS_COMPLETED';
    const ACQUISITION_STATUS_SUSPEND_ON_PLAYING_FAIL = 'AUTO_ACQUISITION_STATUS_SUSPEND_ON_PLAYING_FAIL';
    const ACQUISITION_STATUS_END_LESS_THAN_24_H = 'AUTO_ACQUISITION_STATUS_END_LESS_THAN_24H';
    const ACQUISITION_STATUS_ADVERTISER_CLOSED = 'AUTO_ACQUISITION_STATUS_ADVERTISER_CLOSED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACQUISTION_STATUS_UNKNOW,
            self::ACQUISTION_STATUS_PENDING,
            self::ACQUISTION_STATUS_END_LESS_THAN_24_H,
            self::ACQUISTION_STATUS_END_MORE_THAN_24_H,
            self::ACQUISTION_STATUS_COMPLETED,
            self::ACQUISTION_STATUS_SUSPEND_ON_LEARNING_FAIL,
            self::ACQUISTION_STATUS_SUSPEND_ON_PLAYING_FAIL,
            self::ACQUISTION_STATUS_ADVERTISER_CLOSED,
            self::ACQUISITION_STATUS_PENDING,
            self::ACQUISITION_STATUS_COMPLETED,
            self::ACQUISITION_STATUS_SUSPEND_ON_PLAYING_FAIL,
            self::ACQUISITION_STATUS_END_LESS_THAN_24_H,
            self::ACQUISITION_STATUS_ADVERTISER_CLOSED,
        ];
    }
}


