<?php
/**
 * CanvasPageElementType
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;
use \TencentAds\ObjectSerializer;

/**
 * CanvasPageElementType Class Doc Comment
 *
 * @category Class
 * @description 原生页中组件类型
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CanvasPageElementType
{
    /**
     * Possible values of this enum
     */
    const TOP_IMAGE = 'TOP_IMAGE';
    const TOP_SLIDER = 'TOP_SLIDER';
    const TOP_VIDEO = 'TOP_VIDEO';
    const IMAGE = 'IMAGE';
    const SLIDER = 'SLIDER';
    const VIDEO = 'VIDEO';
    const TEXT = 'TEXT';
    const APP_DOWNLOAD = 'APP_DOWNLOAD';
    const WEAPP = 'WEAPP';
    const GH = 'GH';
    const ENTERPRISE_WX = 'ENTERPRISE_WX';
    const IMAGE_TEXT = 'IMAGE_TEXT';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TOP_IMAGE,
            self::TOP_SLIDER,
            self::TOP_VIDEO,
            self::IMAGE,
            self::SLIDER,
            self::VIDEO,
            self::TEXT,
            self::APP_DOWNLOAD,
            self::WEAPP,
            self::GH,
            self::ENTERPRISE_WX,
            self::IMAGE_TEXT,
        ];
    }
}


