<?php
/**
 * CatalogProductCatalogVertical
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;
use \TencentAds\ObjectSerializer;

/**
 * CatalogProductCatalogVertical Class Doc Comment
 *
 * @category Class
 * @description 商品目录行业类型，详见 &lt;a href&#x3D;&#39;catalog_vertical&#39; target&#x3D;&#39;_blank&#39;&gt;[商品目录行业类型]&lt;/a&gt;
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CatalogProductCatalogVertical
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'UNKNOWN';
    const VERTICAL_EC = 'VERTICAL_EC';
    const VERTICAL_ESTATE = 'VERTICAL_ESTATE';
    const VERTICAL_HOTEL = 'VERTICAL_HOTEL';
    const VERTICAL_TICKET = 'VERTICAL_TICKET';
    const VERTICAL_TRAVEL = 'VERTICAL_TRAVEL';
    const VERTICAL_SCENERY = 'VERTICAL_SCENERY';
    const VERTICAL_VIDEO = 'VERTICAL_VIDEO';
    const VERTICAL_CAR = 'VERTICAL_CAR';
    const VERTICAL_LOCAL_SERVICES = 'VERTICAL_LOCAL_SERVICES';
    const VERTICAL_NEWS_INFORMATION = 'VERTICAL_NEWS_INFORMATION';
    const VERTICAL_BEAUTY_PERSONAL_CARE = 'VERTICAL_BEAUTY_PERSONAL_CARE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::VERTICAL_EC,
            self::VERTICAL_ESTATE,
            self::VERTICAL_HOTEL,
            self::VERTICAL_TICKET,
            self::VERTICAL_TRAVEL,
            self::VERTICAL_SCENERY,
            self::VERTICAL_VIDEO,
            self::VERTICAL_CAR,
            self::VERTICAL_LOCAL_SERVICES,
            self::VERTICAL_NEWS_INFORMATION,
            self::VERTICAL_BEAUTY_PERSONAL_CARE,
        ];
    }
}


