<?php
/**
 * LocalEstimatedamountGetRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;

use \ArrayAccess;
use \TencentAds\ObjectSerializer;

/**
 * LocalEstimatedamountGetRequest Class Doc Comment
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocalEstimatedamountGetRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'LocalEstimatedamountGetRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accountId' => 'int',
        'cityLevel' => '\TencentAds\Model\CityLevel',
        'packageLevel' => '\TencentAds\Model\PackageLevel',
        'poiList' => 'string[]',
        'optimizationGoal' => '\TencentAds\Model\OptimizationGoal',
        'radius' => 'int',
        'age' => '\TencentAds\Model\AgeStruct[]',
        'gender' => 'string[]',
        'beginTime' => 'string',
        'endTime' => 'string',
        'budget' => 'int',
        'localBusinessMode' => '\TencentAds\Model\EcoLocalBusinessMode'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accountId' => 'int64',
        'cityLevel' => null,
        'packageLevel' => null,
        'poiList' => null,
        'optimizationGoal' => null,
        'radius' => 'int64',
        'age' => null,
        'gender' => null,
        'beginTime' => null,
        'endTime' => null,
        'budget' => 'int64',
        'localBusinessMode' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accountId' => 'account_id',
        'cityLevel' => 'city_level',
        'packageLevel' => 'package_level',
        'poiList' => 'poi_list',
        'optimizationGoal' => 'optimization_goal',
        'radius' => 'radius',
        'age' => 'age',
        'gender' => 'gender',
        'beginTime' => 'begin_time',
        'endTime' => 'end_time',
        'budget' => 'budget',
        'localBusinessMode' => 'local_business_mode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accountId' => 'setAccountId',
        'cityLevel' => 'setCityLevel',
        'packageLevel' => 'setPackageLevel',
        'poiList' => 'setPoiList',
        'optimizationGoal' => 'setOptimizationGoal',
        'radius' => 'setRadius',
        'age' => 'setAge',
        'gender' => 'setGender',
        'beginTime' => 'setBeginTime',
        'endTime' => 'setEndTime',
        'budget' => 'setBudget',
        'localBusinessMode' => 'setLocalBusinessMode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accountId' => 'getAccountId',
        'cityLevel' => 'getCityLevel',
        'packageLevel' => 'getPackageLevel',
        'poiList' => 'getPoiList',
        'optimizationGoal' => 'getOptimizationGoal',
        'radius' => 'getRadius',
        'age' => 'getAge',
        'gender' => 'getGender',
        'beginTime' => 'getBeginTime',
        'endTime' => 'getEndTime',
        'budget' => 'getBudget',
        'localBusinessMode' => 'getLocalBusinessMode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accountId'] = isset($data['accountId']) ? $data['accountId'] : null;
        $this->container['cityLevel'] = isset($data['cityLevel']) ? $data['cityLevel'] : null;
        $this->container['packageLevel'] = isset($data['packageLevel']) ? $data['packageLevel'] : null;
        $this->container['poiList'] = isset($data['poiList']) ? $data['poiList'] : null;
        $this->container['optimizationGoal'] = isset($data['optimizationGoal']) ? $data['optimizationGoal'] : null;
        $this->container['radius'] = isset($data['radius']) ? $data['radius'] : null;
        $this->container['age'] = isset($data['age']) ? $data['age'] : null;
        $this->container['gender'] = isset($data['gender']) ? $data['gender'] : null;
        $this->container['beginTime'] = isset($data['beginTime']) ? $data['beginTime'] : null;
        $this->container['endTime'] = isset($data['endTime']) ? $data['endTime'] : null;
        $this->container['budget'] = isset($data['budget']) ? $data['budget'] : null;
        $this->container['localBusinessMode'] = isset($data['localBusinessMode']) ? $data['localBusinessMode'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accountId
     *
     * @return int
     */
    public function getAccountId()
    {
        return $this->container['accountId'];
    }

    /**
     * Sets accountId
     *
     * @param int $accountId accountId
     *
     * @return $this
     */
    public function setAccountId($accountId)
    {
        $this->container['accountId'] = $accountId;

        return $this;
    }

    /**
     * Gets cityLevel
     *
     * @return \TencentAds\Model\CityLevel
     */
    public function getCityLevel()
    {
        return $this->container['cityLevel'];
    }

    /**
     * Sets cityLevel
     *
     * @param \TencentAds\Model\CityLevel $cityLevel cityLevel
     *
     * @return $this
     */
    public function setCityLevel($cityLevel)
    {
        $this->container['cityLevel'] = $cityLevel;

        return $this;
    }

    /**
     * Gets packageLevel
     *
     * @return \TencentAds\Model\PackageLevel
     */
    public function getPackageLevel()
    {
        return $this->container['packageLevel'];
    }

    /**
     * Sets packageLevel
     *
     * @param \TencentAds\Model\PackageLevel $packageLevel packageLevel
     *
     * @return $this
     */
    public function setPackageLevel($packageLevel)
    {
        $this->container['packageLevel'] = $packageLevel;

        return $this;
    }

    /**
     * Gets poiList
     *
     * @return string[]
     */
    public function getPoiList()
    {
        return $this->container['poiList'];
    }

    /**
     * Sets poiList
     *
     * @param string[] $poiList poiList
     *
     * @return $this
     */
    public function setPoiList($poiList)
    {
        $this->container['poiList'] = $poiList;

        return $this;
    }

    /**
     * Gets optimizationGoal
     *
     * @return \TencentAds\Model\OptimizationGoal
     */
    public function getOptimizationGoal()
    {
        return $this->container['optimizationGoal'];
    }

    /**
     * Sets optimizationGoal
     *
     * @param \TencentAds\Model\OptimizationGoal $optimizationGoal optimizationGoal
     *
     * @return $this
     */
    public function setOptimizationGoal($optimizationGoal)
    {
        $this->container['optimizationGoal'] = $optimizationGoal;

        return $this;
    }

    /**
     * Gets radius
     *
     * @return int
     */
    public function getRadius()
    {
        return $this->container['radius'];
    }

    /**
     * Sets radius
     *
     * @param int $radius radius
     *
     * @return $this
     */
    public function setRadius($radius)
    {
        $this->container['radius'] = $radius;

        return $this;
    }

    /**
     * Gets age
     *
     * @return \TencentAds\Model\AgeStruct[]
     */
    public function getAge()
    {
        return $this->container['age'];
    }

    /**
     * Sets age
     *
     * @param \TencentAds\Model\AgeStruct[] $age age
     *
     * @return $this
     */
    public function setAge($age)
    {
        $this->container['age'] = $age;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string[]
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string[] $gender gender
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets beginTime
     *
     * @return string
     */
    public function getBeginTime()
    {
        return $this->container['beginTime'];
    }

    /**
     * Sets beginTime
     *
     * @param string $beginTime beginTime
     *
     * @return $this
     */
    public function setBeginTime($beginTime)
    {
        $this->container['beginTime'] = $beginTime;

        return $this;
    }

    /**
     * Gets endTime
     *
     * @return string
     */
    public function getEndTime()
    {
        return $this->container['endTime'];
    }

    /**
     * Sets endTime
     *
     * @param string $endTime endTime
     *
     * @return $this
     */
    public function setEndTime($endTime)
    {
        $this->container['endTime'] = $endTime;

        return $this;
    }

    /**
     * Gets budget
     *
     * @return int
     */
    public function getBudget()
    {
        return $this->container['budget'];
    }

    /**
     * Sets budget
     *
     * @param int $budget budget
     *
     * @return $this
     */
    public function setBudget($budget)
    {
        $this->container['budget'] = $budget;

        return $this;
    }

    /**
     * Gets localBusinessMode
     *
     * @return \TencentAds\Model\EcoLocalBusinessMode
     */
    public function getLocalBusinessMode()
    {
        return $this->container['localBusinessMode'];
    }

    /**
     * Sets localBusinessMode
     *
     * @param \TencentAds\Model\EcoLocalBusinessMode $localBusinessMode localBusinessMode
     *
     * @return $this
     */
    public function setLocalBusinessMode($localBusinessMode)
    {
        $this->container['localBusinessMode'] = $localBusinessMode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


