<?php
/**
 * RevisedAdcreativeElements
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;

use \ArrayAccess;
use \TencentAds\ObjectSerializer;

/**
 * RevisedAdcreativeElements Class Doc Comment
 *
 * @category Class
 * @description 修改后的创意元素，填写要求同adcreative_elements，当且仅当 online_enabled &#x3D; true 时，此字段允许写入
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RevisedAdcreativeElements implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'revised_adcreative_elements';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'image' => 'string',
        'image2' => 'string',
        'image3' => 'string',
        'title' => 'string',
        'description' => 'string',
        'corporate' => '\TencentAds\Model\AdcreativeCorporate',
        'video' => 'string',
        'deepLinkType' => 'string',
        'linkNameType' => '\TencentAds\Model\LinkNameType',
        'imageList' => 'string[]',
        'elementStory' => '\TencentAds\Model\AdcreativeElementStoryArrayItem[]',
        'url' => 'string',
        'buttonText' => 'string',
        'bottomText' => 'string',
        'excitationText' => 'string',
        'countdownBegin' => 'int',
        'countdownExpiringTimestamp' => 'int',
        'countdownPrice' => 'string',
        'countdownTimeType' => '\TencentAds\Model\AdCreativeCountdownTimeType',
        'miniProgramId' => 'string',
        'miniProgramPath' => 'string',
        'miniProgramPaths' => 'string[]',
        'label' => '\TencentAds\Model\CreativeLabel[]',
        'productTags' => 'string[]',
        'logoDescription' => 'string',
        'logo' => 'string',
        'leftBottomTxt' => 'string',
        'animationEffect' => 'string',
        'phone' => 'string',
        'shortVideoStruct' => '\TencentAds\Model\ShortVideoStruct',
        'longVideoStruct' => '\TencentAds\Model\LongVideoStruct',
        'bannerContent' => '\TencentAds\Model\AdcreativeBannerContent',
        'cardContent' => '\TencentAds\Model\AdcreativeCardContent',
        'videoPopupUrl' => 'string',
        'videoPopupButton' => '\TencentAds\Model\AdcreativeVideoPopupButton',
        'buttonUrl' => 'string',
        'brand' => '\TencentAds\Model\AdCreativeBrand',
        'caption' => 'string',
        'labelledImg' => '\TencentAds\Model\AdcreativeLabelledImg',
        'fullScreenImage' => 'string',
        'zipUrl' => 'string',
        'endPage' => '\TencentAds\Model\AdCreativeEndPage',
        'headLine' => 'string',
        'shopImageStruct' => '\TencentAds\Model\AdCreativeShopImageStruct',
        'chosenButton' => '\TencentAds\Model\ChosenButton',
        'livingDescStruct' => '\TencentAds\Model\AdCreativeLivingDescStruct',
        'floatingZoneStruct' => '\TencentAds\Model\FloatingZone',
        'canvasShareImage' => 'string',
        'wegameInfoSpec' => '\TencentAds\Model\WegameInfoSpec',
        'wechatChannelsSpec' => '\TencentAds\Model\AdCreativeWechatChannelsSpec',
        'finderObjectVisibility' => 'bool',
        'actionButtonComponentOptions' => '\TencentAds\Model\ActionButtonComponentOption[]',
        'chosenButtonComponentOptions' => '\TencentAds\Model\ChosenButtonComponentOption[]',
        'video2ComponentOptions' => '\TencentAds\Model\VideoComponentOption[]',
        'imageListJumpInfo' => '\TencentAds\Model\LandingPageStructure[]',
        'originVideo' => 'string',
        'redEnvelopeStruct' => '\TencentAds\Model\RedEnvelopeStruct',
        'buttonTextJumpInfo' => '\TencentAds\Model\LandingPageStructure',
        'promotionSublinkComponentOptions' => '\TencentAds\Model\PromotionSublinkComponentOption[]',
        'wxgamePlayablePageSpec' => '\TencentAds\Model\WxgamePlayablePageSpec',
        'mainJumpInfo' => '\TencentAds\Model\LandingPageStructure[]',
        'mdpaTitleComponentOptions' => '\TencentAds\Model\MdpaTitleComponentOption[]',
        'mdpaDescComponentOptions' => '\TencentAds\Model\MdpaDescComponentOption[]',
        'listSublinkComponentOptions' => '\TencentAds\Model\ListSublinkComponentOption[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'image' => null,
        'image2' => null,
        'image3' => null,
        'title' => null,
        'description' => null,
        'corporate' => null,
        'video' => null,
        'deepLinkType' => null,
        'linkNameType' => null,
        'imageList' => null,
        'elementStory' => null,
        'url' => null,
        'buttonText' => null,
        'bottomText' => null,
        'excitationText' => null,
        'countdownBegin' => 'int64',
        'countdownExpiringTimestamp' => 'int64',
        'countdownPrice' => null,
        'countdownTimeType' => null,
        'miniProgramId' => null,
        'miniProgramPath' => null,
        'miniProgramPaths' => null,
        'label' => null,
        'productTags' => null,
        'logoDescription' => null,
        'logo' => null,
        'leftBottomTxt' => null,
        'animationEffect' => null,
        'phone' => null,
        'shortVideoStruct' => null,
        'longVideoStruct' => null,
        'bannerContent' => null,
        'cardContent' => null,
        'videoPopupUrl' => null,
        'videoPopupButton' => null,
        'buttonUrl' => null,
        'brand' => null,
        'caption' => null,
        'labelledImg' => null,
        'fullScreenImage' => null,
        'zipUrl' => null,
        'endPage' => null,
        'headLine' => null,
        'shopImageStruct' => null,
        'chosenButton' => null,
        'livingDescStruct' => null,
        'floatingZoneStruct' => null,
        'canvasShareImage' => null,
        'wegameInfoSpec' => null,
        'wechatChannelsSpec' => null,
        'finderObjectVisibility' => null,
        'actionButtonComponentOptions' => null,
        'chosenButtonComponentOptions' => null,
        'video2ComponentOptions' => null,
        'imageListJumpInfo' => null,
        'originVideo' => null,
        'redEnvelopeStruct' => null,
        'buttonTextJumpInfo' => null,
        'promotionSublinkComponentOptions' => null,
        'wxgamePlayablePageSpec' => null,
        'mainJumpInfo' => null,
        'mdpaTitleComponentOptions' => null,
        'mdpaDescComponentOptions' => null,
        'listSublinkComponentOptions' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'image' => 'image',
        'image2' => 'image2',
        'image3' => 'image3',
        'title' => 'title',
        'description' => 'description',
        'corporate' => 'corporate',
        'video' => 'video',
        'deepLinkType' => 'deep_link_type',
        'linkNameType' => 'link_name_type',
        'imageList' => 'image_list',
        'elementStory' => 'element_story',
        'url' => 'url',
        'buttonText' => 'button_text',
        'bottomText' => 'bottom_text',
        'excitationText' => 'excitation_text',
        'countdownBegin' => 'countdown_begin',
        'countdownExpiringTimestamp' => 'countdown_expiring_timestamp',
        'countdownPrice' => 'countdown_price',
        'countdownTimeType' => 'countdown_time_type',
        'miniProgramId' => 'mini_program_id',
        'miniProgramPath' => 'mini_program_path',
        'miniProgramPaths' => 'mini_program_paths',
        'label' => 'label',
        'productTags' => 'product_tags',
        'logoDescription' => 'logo_description',
        'logo' => 'logo',
        'leftBottomTxt' => 'left_bottom_txt',
        'animationEffect' => 'animation_effect',
        'phone' => 'phone',
        'shortVideoStruct' => 'short_video_struct',
        'longVideoStruct' => 'long_video_struct',
        'bannerContent' => 'banner_content',
        'cardContent' => 'card_content',
        'videoPopupUrl' => 'video_popup_url',
        'videoPopupButton' => 'video_popup_button',
        'buttonUrl' => 'button_url',
        'brand' => 'brand',
        'caption' => 'caption',
        'labelledImg' => 'labelled_img',
        'fullScreenImage' => 'full_screen_image',
        'zipUrl' => 'zip_url',
        'endPage' => 'end_page',
        'headLine' => 'head_line',
        'shopImageStruct' => 'shop_image_struct',
        'chosenButton' => 'chosen_button',
        'livingDescStruct' => 'living_desc_struct',
        'floatingZoneStruct' => 'floating_zone_struct',
        'canvasShareImage' => 'canvas_share_image',
        'wegameInfoSpec' => 'wegame_info_spec',
        'wechatChannelsSpec' => 'wechat_channels_spec',
        'finderObjectVisibility' => 'finder_object_visibility',
        'actionButtonComponentOptions' => 'action_button_component_options',
        'chosenButtonComponentOptions' => 'chosen_button_component_options',
        'video2ComponentOptions' => 'video2_component_options',
        'imageListJumpInfo' => 'image_list_jump_info',
        'originVideo' => 'origin_video',
        'redEnvelopeStruct' => 'red_envelope_struct',
        'buttonTextJumpInfo' => 'button_text_jump_info',
        'promotionSublinkComponentOptions' => 'promotion_sublink_component_options',
        'wxgamePlayablePageSpec' => 'wxgame_playable_page_spec',
        'mainJumpInfo' => 'main_jump_info',
        'mdpaTitleComponentOptions' => 'mdpa_title_component_options',
        'mdpaDescComponentOptions' => 'mdpa_desc_component_options',
        'listSublinkComponentOptions' => 'list_sublink_component_options'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'image' => 'setImage',
        'image2' => 'setImage2',
        'image3' => 'setImage3',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'corporate' => 'setCorporate',
        'video' => 'setVideo',
        'deepLinkType' => 'setDeepLinkType',
        'linkNameType' => 'setLinkNameType',
        'imageList' => 'setImageList',
        'elementStory' => 'setElementStory',
        'url' => 'setUrl',
        'buttonText' => 'setButtonText',
        'bottomText' => 'setBottomText',
        'excitationText' => 'setExcitationText',
        'countdownBegin' => 'setCountdownBegin',
        'countdownExpiringTimestamp' => 'setCountdownExpiringTimestamp',
        'countdownPrice' => 'setCountdownPrice',
        'countdownTimeType' => 'setCountdownTimeType',
        'miniProgramId' => 'setMiniProgramId',
        'miniProgramPath' => 'setMiniProgramPath',
        'miniProgramPaths' => 'setMiniProgramPaths',
        'label' => 'setLabel',
        'productTags' => 'setProductTags',
        'logoDescription' => 'setLogoDescription',
        'logo' => 'setLogo',
        'leftBottomTxt' => 'setLeftBottomTxt',
        'animationEffect' => 'setAnimationEffect',
        'phone' => 'setPhone',
        'shortVideoStruct' => 'setShortVideoStruct',
        'longVideoStruct' => 'setLongVideoStruct',
        'bannerContent' => 'setBannerContent',
        'cardContent' => 'setCardContent',
        'videoPopupUrl' => 'setVideoPopupUrl',
        'videoPopupButton' => 'setVideoPopupButton',
        'buttonUrl' => 'setButtonUrl',
        'brand' => 'setBrand',
        'caption' => 'setCaption',
        'labelledImg' => 'setLabelledImg',
        'fullScreenImage' => 'setFullScreenImage',
        'zipUrl' => 'setZipUrl',
        'endPage' => 'setEndPage',
        'headLine' => 'setHeadLine',
        'shopImageStruct' => 'setShopImageStruct',
        'chosenButton' => 'setChosenButton',
        'livingDescStruct' => 'setLivingDescStruct',
        'floatingZoneStruct' => 'setFloatingZoneStruct',
        'canvasShareImage' => 'setCanvasShareImage',
        'wegameInfoSpec' => 'setWegameInfoSpec',
        'wechatChannelsSpec' => 'setWechatChannelsSpec',
        'finderObjectVisibility' => 'setFinderObjectVisibility',
        'actionButtonComponentOptions' => 'setActionButtonComponentOptions',
        'chosenButtonComponentOptions' => 'setChosenButtonComponentOptions',
        'video2ComponentOptions' => 'setVideo2ComponentOptions',
        'imageListJumpInfo' => 'setImageListJumpInfo',
        'originVideo' => 'setOriginVideo',
        'redEnvelopeStruct' => 'setRedEnvelopeStruct',
        'buttonTextJumpInfo' => 'setButtonTextJumpInfo',
        'promotionSublinkComponentOptions' => 'setPromotionSublinkComponentOptions',
        'wxgamePlayablePageSpec' => 'setWxgamePlayablePageSpec',
        'mainJumpInfo' => 'setMainJumpInfo',
        'mdpaTitleComponentOptions' => 'setMdpaTitleComponentOptions',
        'mdpaDescComponentOptions' => 'setMdpaDescComponentOptions',
        'listSublinkComponentOptions' => 'setListSublinkComponentOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'image' => 'getImage',
        'image2' => 'getImage2',
        'image3' => 'getImage3',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'corporate' => 'getCorporate',
        'video' => 'getVideo',
        'deepLinkType' => 'getDeepLinkType',
        'linkNameType' => 'getLinkNameType',
        'imageList' => 'getImageList',
        'elementStory' => 'getElementStory',
        'url' => 'getUrl',
        'buttonText' => 'getButtonText',
        'bottomText' => 'getBottomText',
        'excitationText' => 'getExcitationText',
        'countdownBegin' => 'getCountdownBegin',
        'countdownExpiringTimestamp' => 'getCountdownExpiringTimestamp',
        'countdownPrice' => 'getCountdownPrice',
        'countdownTimeType' => 'getCountdownTimeType',
        'miniProgramId' => 'getMiniProgramId',
        'miniProgramPath' => 'getMiniProgramPath',
        'miniProgramPaths' => 'getMiniProgramPaths',
        'label' => 'getLabel',
        'productTags' => 'getProductTags',
        'logoDescription' => 'getLogoDescription',
        'logo' => 'getLogo',
        'leftBottomTxt' => 'getLeftBottomTxt',
        'animationEffect' => 'getAnimationEffect',
        'phone' => 'getPhone',
        'shortVideoStruct' => 'getShortVideoStruct',
        'longVideoStruct' => 'getLongVideoStruct',
        'bannerContent' => 'getBannerContent',
        'cardContent' => 'getCardContent',
        'videoPopupUrl' => 'getVideoPopupUrl',
        'videoPopupButton' => 'getVideoPopupButton',
        'buttonUrl' => 'getButtonUrl',
        'brand' => 'getBrand',
        'caption' => 'getCaption',
        'labelledImg' => 'getLabelledImg',
        'fullScreenImage' => 'getFullScreenImage',
        'zipUrl' => 'getZipUrl',
        'endPage' => 'getEndPage',
        'headLine' => 'getHeadLine',
        'shopImageStruct' => 'getShopImageStruct',
        'chosenButton' => 'getChosenButton',
        'livingDescStruct' => 'getLivingDescStruct',
        'floatingZoneStruct' => 'getFloatingZoneStruct',
        'canvasShareImage' => 'getCanvasShareImage',
        'wegameInfoSpec' => 'getWegameInfoSpec',
        'wechatChannelsSpec' => 'getWechatChannelsSpec',
        'finderObjectVisibility' => 'getFinderObjectVisibility',
        'actionButtonComponentOptions' => 'getActionButtonComponentOptions',
        'chosenButtonComponentOptions' => 'getChosenButtonComponentOptions',
        'video2ComponentOptions' => 'getVideo2ComponentOptions',
        'imageListJumpInfo' => 'getImageListJumpInfo',
        'originVideo' => 'getOriginVideo',
        'redEnvelopeStruct' => 'getRedEnvelopeStruct',
        'buttonTextJumpInfo' => 'getButtonTextJumpInfo',
        'promotionSublinkComponentOptions' => 'getPromotionSublinkComponentOptions',
        'wxgamePlayablePageSpec' => 'getWxgamePlayablePageSpec',
        'mainJumpInfo' => 'getMainJumpInfo',
        'mdpaTitleComponentOptions' => 'getMdpaTitleComponentOptions',
        'mdpaDescComponentOptions' => 'getMdpaDescComponentOptions',
        'listSublinkComponentOptions' => 'getListSublinkComponentOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
        $this->container['image2'] = isset($data['image2']) ? $data['image2'] : null;
        $this->container['image3'] = isset($data['image3']) ? $data['image3'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['corporate'] = isset($data['corporate']) ? $data['corporate'] : null;
        $this->container['video'] = isset($data['video']) ? $data['video'] : null;
        $this->container['deepLinkType'] = isset($data['deepLinkType']) ? $data['deepLinkType'] : null;
        $this->container['linkNameType'] = isset($data['linkNameType']) ? $data['linkNameType'] : null;
        $this->container['imageList'] = isset($data['imageList']) ? $data['imageList'] : null;
        $this->container['elementStory'] = isset($data['elementStory']) ? $data['elementStory'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['buttonText'] = isset($data['buttonText']) ? $data['buttonText'] : null;
        $this->container['bottomText'] = isset($data['bottomText']) ? $data['bottomText'] : null;
        $this->container['excitationText'] = isset($data['excitationText']) ? $data['excitationText'] : null;
        $this->container['countdownBegin'] = isset($data['countdownBegin']) ? $data['countdownBegin'] : null;
        $this->container['countdownExpiringTimestamp'] = isset($data['countdownExpiringTimestamp']) ? $data['countdownExpiringTimestamp'] : null;
        $this->container['countdownPrice'] = isset($data['countdownPrice']) ? $data['countdownPrice'] : null;
        $this->container['countdownTimeType'] = isset($data['countdownTimeType']) ? $data['countdownTimeType'] : null;
        $this->container['miniProgramId'] = isset($data['miniProgramId']) ? $data['miniProgramId'] : null;
        $this->container['miniProgramPath'] = isset($data['miniProgramPath']) ? $data['miniProgramPath'] : null;
        $this->container['miniProgramPaths'] = isset($data['miniProgramPaths']) ? $data['miniProgramPaths'] : null;
        $this->container['label'] = isset($data['label']) ? $data['label'] : null;
        $this->container['productTags'] = isset($data['productTags']) ? $data['productTags'] : null;
        $this->container['logoDescription'] = isset($data['logoDescription']) ? $data['logoDescription'] : null;
        $this->container['logo'] = isset($data['logo']) ? $data['logo'] : null;
        $this->container['leftBottomTxt'] = isset($data['leftBottomTxt']) ? $data['leftBottomTxt'] : null;
        $this->container['animationEffect'] = isset($data['animationEffect']) ? $data['animationEffect'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['shortVideoStruct'] = isset($data['shortVideoStruct']) ? $data['shortVideoStruct'] : null;
        $this->container['longVideoStruct'] = isset($data['longVideoStruct']) ? $data['longVideoStruct'] : null;
        $this->container['bannerContent'] = isset($data['bannerContent']) ? $data['bannerContent'] : null;
        $this->container['cardContent'] = isset($data['cardContent']) ? $data['cardContent'] : null;
        $this->container['videoPopupUrl'] = isset($data['videoPopupUrl']) ? $data['videoPopupUrl'] : null;
        $this->container['videoPopupButton'] = isset($data['videoPopupButton']) ? $data['videoPopupButton'] : null;
        $this->container['buttonUrl'] = isset($data['buttonUrl']) ? $data['buttonUrl'] : null;
        $this->container['brand'] = isset($data['brand']) ? $data['brand'] : null;
        $this->container['caption'] = isset($data['caption']) ? $data['caption'] : null;
        $this->container['labelledImg'] = isset($data['labelledImg']) ? $data['labelledImg'] : null;
        $this->container['fullScreenImage'] = isset($data['fullScreenImage']) ? $data['fullScreenImage'] : null;
        $this->container['zipUrl'] = isset($data['zipUrl']) ? $data['zipUrl'] : null;
        $this->container['endPage'] = isset($data['endPage']) ? $data['endPage'] : null;
        $this->container['headLine'] = isset($data['headLine']) ? $data['headLine'] : null;
        $this->container['shopImageStruct'] = isset($data['shopImageStruct']) ? $data['shopImageStruct'] : null;
        $this->container['chosenButton'] = isset($data['chosenButton']) ? $data['chosenButton'] : null;
        $this->container['livingDescStruct'] = isset($data['livingDescStruct']) ? $data['livingDescStruct'] : null;
        $this->container['floatingZoneStruct'] = isset($data['floatingZoneStruct']) ? $data['floatingZoneStruct'] : null;
        $this->container['canvasShareImage'] = isset($data['canvasShareImage']) ? $data['canvasShareImage'] : null;
        $this->container['wegameInfoSpec'] = isset($data['wegameInfoSpec']) ? $data['wegameInfoSpec'] : null;
        $this->container['wechatChannelsSpec'] = isset($data['wechatChannelsSpec']) ? $data['wechatChannelsSpec'] : null;
        $this->container['finderObjectVisibility'] = isset($data['finderObjectVisibility']) ? $data['finderObjectVisibility'] : null;
        $this->container['actionButtonComponentOptions'] = isset($data['actionButtonComponentOptions']) ? $data['actionButtonComponentOptions'] : null;
        $this->container['chosenButtonComponentOptions'] = isset($data['chosenButtonComponentOptions']) ? $data['chosenButtonComponentOptions'] : null;
        $this->container['video2ComponentOptions'] = isset($data['video2ComponentOptions']) ? $data['video2ComponentOptions'] : null;
        $this->container['imageListJumpInfo'] = isset($data['imageListJumpInfo']) ? $data['imageListJumpInfo'] : null;
        $this->container['originVideo'] = isset($data['originVideo']) ? $data['originVideo'] : null;
        $this->container['redEnvelopeStruct'] = isset($data['redEnvelopeStruct']) ? $data['redEnvelopeStruct'] : null;
        $this->container['buttonTextJumpInfo'] = isset($data['buttonTextJumpInfo']) ? $data['buttonTextJumpInfo'] : null;
        $this->container['promotionSublinkComponentOptions'] = isset($data['promotionSublinkComponentOptions']) ? $data['promotionSublinkComponentOptions'] : null;
        $this->container['wxgamePlayablePageSpec'] = isset($data['wxgamePlayablePageSpec']) ? $data['wxgamePlayablePageSpec'] : null;
        $this->container['mainJumpInfo'] = isset($data['mainJumpInfo']) ? $data['mainJumpInfo'] : null;
        $this->container['mdpaTitleComponentOptions'] = isset($data['mdpaTitleComponentOptions']) ? $data['mdpaTitleComponentOptions'] : null;
        $this->container['mdpaDescComponentOptions'] = isset($data['mdpaDescComponentOptions']) ? $data['mdpaDescComponentOptions'] : null;
        $this->container['listSublinkComponentOptions'] = isset($data['listSublinkComponentOptions']) ? $data['listSublinkComponentOptions'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets image
     *
     * @return string|mixed
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param string|mixed $image image
     *
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets image2
     *
     * @return string|mixed
     */
    public function getImage2()
    {
        return $this->container['image2'];
    }

    /**
     * Sets image2
     *
     * @param string|mixed $image2 image2
     *
     * @return $this
     */
    public function setImage2($image2)
    {
        $this->container['image2'] = $image2;

        return $this;
    }

    /**
     * Gets image3
     *
     * @return string|mixed
     */
    public function getImage3()
    {
        return $this->container['image3'];
    }

    /**
     * Sets image3
     *
     * @param string|mixed $image3 image3
     *
     * @return $this
     */
    public function setImage3($image3)
    {
        $this->container['image3'] = $image3;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|mixed
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|mixed $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|mixed
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|mixed $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets corporate
     *
     * @return \TencentAds\Model\AdcreativeCorporate|mixed
     */
    public function getCorporate()
    {
        return $this->container['corporate'];
    }

    /**
     * Sets corporate
     *
     * @param \TencentAds\Model\AdcreativeCorporate|mixed $corporate corporate
     *
     * @return $this
     */
    public function setCorporate($corporate)
    {
        $this->container['corporate'] = $corporate;

        return $this;
    }

    /**
     * Gets video
     *
     * @return string|mixed
     */
    public function getVideo()
    {
        return $this->container['video'];
    }

    /**
     * Sets video
     *
     * @param string|mixed $video video
     *
     * @return $this
     */
    public function setVideo($video)
    {
        $this->container['video'] = $video;

        return $this;
    }

    /**
     * Gets deepLinkType
     *
     * @return string|mixed
     */
    public function getDeepLinkType()
    {
        return $this->container['deepLinkType'];
    }

    /**
     * Sets deepLinkType
     *
     * @param string|mixed $deepLinkType deepLinkType
     *
     * @return $this
     */
    public function setDeepLinkType($deepLinkType)
    {
        $this->container['deepLinkType'] = $deepLinkType;

        return $this;
    }

    /**
     * Gets linkNameType
     *
     * @return \TencentAds\Model\LinkNameType|mixed
     */
    public function getLinkNameType()
    {
        return $this->container['linkNameType'];
    }

    /**
     * Sets linkNameType
     *
     * @param \TencentAds\Model\LinkNameType|mixed $linkNameType linkNameType
     *
     * @return $this
     */
    public function setLinkNameType($linkNameType)
    {
        $this->container['linkNameType'] = $linkNameType;

        return $this;
    }

    /**
     * Gets imageList
     *
     * @return string[]|mixed
     */
    public function getImageList()
    {
        return $this->container['imageList'];
    }

    /**
     * Sets imageList
     *
     * @param string[]|mixed $imageList imageList
     *
     * @return $this
     */
    public function setImageList($imageList)
    {
        $this->container['imageList'] = $imageList;

        return $this;
    }

    /**
     * Gets elementStory
     *
     * @return \TencentAds\Model\AdcreativeElementStoryArrayItem[]|mixed
     */
    public function getElementStory()
    {
        return $this->container['elementStory'];
    }

    /**
     * Sets elementStory
     *
     * @param \TencentAds\Model\AdcreativeElementStoryArrayItem[]|mixed $elementStory elementStory
     *
     * @return $this
     */
    public function setElementStory($elementStory)
    {
        $this->container['elementStory'] = $elementStory;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|mixed
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|mixed $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets buttonText
     *
     * @return string|mixed
     */
    public function getButtonText()
    {
        return $this->container['buttonText'];
    }

    /**
     * Sets buttonText
     *
     * @param string|mixed $buttonText buttonText
     *
     * @return $this
     */
    public function setButtonText($buttonText)
    {
        $this->container['buttonText'] = $buttonText;

        return $this;
    }

    /**
     * Gets bottomText
     *
     * @return string|mixed
     */
    public function getBottomText()
    {
        return $this->container['bottomText'];
    }

    /**
     * Sets bottomText
     *
     * @param string|mixed $bottomText bottomText
     *
     * @return $this
     */
    public function setBottomText($bottomText)
    {
        $this->container['bottomText'] = $bottomText;

        return $this;
    }

    /**
     * Gets excitationText
     *
     * @return string|mixed
     */
    public function getExcitationText()
    {
        return $this->container['excitationText'];
    }

    /**
     * Sets excitationText
     *
     * @param string|mixed $excitationText excitationText
     *
     * @return $this
     */
    public function setExcitationText($excitationText)
    {
        $this->container['excitationText'] = $excitationText;

        return $this;
    }

    /**
     * Gets countdownBegin
     *
     * @return int|mixed
     */
    public function getCountdownBegin()
    {
        return $this->container['countdownBegin'];
    }

    /**
     * Sets countdownBegin
     *
     * @param int|mixed $countdownBegin countdownBegin
     *
     * @return $this
     */
    public function setCountdownBegin($countdownBegin)
    {
        $this->container['countdownBegin'] = $countdownBegin;

        return $this;
    }

    /**
     * Gets countdownExpiringTimestamp
     *
     * @return int|mixed
     */
    public function getCountdownExpiringTimestamp()
    {
        return $this->container['countdownExpiringTimestamp'];
    }

    /**
     * Sets countdownExpiringTimestamp
     *
     * @param int|mixed $countdownExpiringTimestamp countdownExpiringTimestamp
     *
     * @return $this
     */
    public function setCountdownExpiringTimestamp($countdownExpiringTimestamp)
    {
        $this->container['countdownExpiringTimestamp'] = $countdownExpiringTimestamp;

        return $this;
    }

    /**
     * Gets countdownPrice
     *
     * @return string|mixed
     */
    public function getCountdownPrice()
    {
        return $this->container['countdownPrice'];
    }

    /**
     * Sets countdownPrice
     *
     * @param string|mixed $countdownPrice countdownPrice
     *
     * @return $this
     */
    public function setCountdownPrice($countdownPrice)
    {
        $this->container['countdownPrice'] = $countdownPrice;

        return $this;
    }

    /**
     * Gets countdownTimeType
     *
     * @return \TencentAds\Model\AdCreativeCountdownTimeType|mixed
     */
    public function getCountdownTimeType()
    {
        return $this->container['countdownTimeType'];
    }

    /**
     * Sets countdownTimeType
     *
     * @param \TencentAds\Model\AdCreativeCountdownTimeType|mixed $countdownTimeType countdownTimeType
     *
     * @return $this
     */
    public function setCountdownTimeType($countdownTimeType)
    {
        $this->container['countdownTimeType'] = $countdownTimeType;

        return $this;
    }

    /**
     * Gets miniProgramId
     *
     * @return string|mixed
     */
    public function getMiniProgramId()
    {
        return $this->container['miniProgramId'];
    }

    /**
     * Sets miniProgramId
     *
     * @param string|mixed $miniProgramId miniProgramId
     *
     * @return $this
     */
    public function setMiniProgramId($miniProgramId)
    {
        $this->container['miniProgramId'] = $miniProgramId;

        return $this;
    }

    /**
     * Gets miniProgramPath
     *
     * @return string|mixed
     */
    public function getMiniProgramPath()
    {
        return $this->container['miniProgramPath'];
    }

    /**
     * Sets miniProgramPath
     *
     * @param string|mixed $miniProgramPath miniProgramPath
     *
     * @return $this
     */
    public function setMiniProgramPath($miniProgramPath)
    {
        $this->container['miniProgramPath'] = $miniProgramPath;

        return $this;
    }

    /**
     * Gets miniProgramPaths
     *
     * @return string[]|mixed
     */
    public function getMiniProgramPaths()
    {
        return $this->container['miniProgramPaths'];
    }

    /**
     * Sets miniProgramPaths
     *
     * @param string[]|mixed $miniProgramPaths miniProgramPaths
     *
     * @return $this
     */
    public function setMiniProgramPaths($miniProgramPaths)
    {
        $this->container['miniProgramPaths'] = $miniProgramPaths;

        return $this;
    }

    /**
     * Gets label
     *
     * @return \TencentAds\Model\CreativeLabel[]|mixed
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param \TencentAds\Model\CreativeLabel[]|mixed $label label
     *
     * @return $this
     */
    public function setLabel($label)
    {
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets productTags
     *
     * @return string[]|mixed
     */
    public function getProductTags()
    {
        return $this->container['productTags'];
    }

    /**
     * Sets productTags
     *
     * @param string[]|mixed $productTags productTags
     *
     * @return $this
     */
    public function setProductTags($productTags)
    {
        $this->container['productTags'] = $productTags;

        return $this;
    }

    /**
     * Gets logoDescription
     *
     * @return string|mixed
     */
    public function getLogoDescription()
    {
        return $this->container['logoDescription'];
    }

    /**
     * Sets logoDescription
     *
     * @param string|mixed $logoDescription logoDescription
     *
     * @return $this
     */
    public function setLogoDescription($logoDescription)
    {
        $this->container['logoDescription'] = $logoDescription;

        return $this;
    }

    /**
     * Gets logo
     *
     * @return string|mixed
     */
    public function getLogo()
    {
        return $this->container['logo'];
    }

    /**
     * Sets logo
     *
     * @param string|mixed $logo logo
     *
     * @return $this
     */
    public function setLogo($logo)
    {
        $this->container['logo'] = $logo;

        return $this;
    }

    /**
     * Gets leftBottomTxt
     *
     * @return string|mixed
     */
    public function getLeftBottomTxt()
    {
        return $this->container['leftBottomTxt'];
    }

    /**
     * Sets leftBottomTxt
     *
     * @param string|mixed $leftBottomTxt leftBottomTxt
     *
     * @return $this
     */
    public function setLeftBottomTxt($leftBottomTxt)
    {
        $this->container['leftBottomTxt'] = $leftBottomTxt;

        return $this;
    }

    /**
     * Gets animationEffect
     *
     * @return string|mixed
     */
    public function getAnimationEffect()
    {
        return $this->container['animationEffect'];
    }

    /**
     * Sets animationEffect
     *
     * @param string|mixed $animationEffect animationEffect
     *
     * @return $this
     */
    public function setAnimationEffect($animationEffect)
    {
        $this->container['animationEffect'] = $animationEffect;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|mixed
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|mixed $phone phone
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets shortVideoStruct
     *
     * @return \TencentAds\Model\ShortVideoStruct|mixed
     */
    public function getShortVideoStruct()
    {
        return $this->container['shortVideoStruct'];
    }

    /**
     * Sets shortVideoStruct
     *
     * @param \TencentAds\Model\ShortVideoStruct|mixed $shortVideoStruct shortVideoStruct
     *
     * @return $this
     */
    public function setShortVideoStruct($shortVideoStruct)
    {
        $this->container['shortVideoStruct'] = $shortVideoStruct;

        return $this;
    }

    /**
     * Gets longVideoStruct
     *
     * @return \TencentAds\Model\LongVideoStruct|mixed
     */
    public function getLongVideoStruct()
    {
        return $this->container['longVideoStruct'];
    }

    /**
     * Sets longVideoStruct
     *
     * @param \TencentAds\Model\LongVideoStruct|mixed $longVideoStruct longVideoStruct
     *
     * @return $this
     */
    public function setLongVideoStruct($longVideoStruct)
    {
        $this->container['longVideoStruct'] = $longVideoStruct;

        return $this;
    }

    /**
     * Gets bannerContent
     *
     * @return \TencentAds\Model\AdcreativeBannerContent|mixed
     */
    public function getBannerContent()
    {
        return $this->container['bannerContent'];
    }

    /**
     * Sets bannerContent
     *
     * @param \TencentAds\Model\AdcreativeBannerContent|mixed $bannerContent bannerContent
     *
     * @return $this
     */
    public function setBannerContent($bannerContent)
    {
        $this->container['bannerContent'] = $bannerContent;

        return $this;
    }

    /**
     * Gets cardContent
     *
     * @return \TencentAds\Model\AdcreativeCardContent|mixed
     */
    public function getCardContent()
    {
        return $this->container['cardContent'];
    }

    /**
     * Sets cardContent
     *
     * @param \TencentAds\Model\AdcreativeCardContent|mixed $cardContent cardContent
     *
     * @return $this
     */
    public function setCardContent($cardContent)
    {
        $this->container['cardContent'] = $cardContent;

        return $this;
    }

    /**
     * Gets videoPopupUrl
     *
     * @return string|mixed
     */
    public function getVideoPopupUrl()
    {
        return $this->container['videoPopupUrl'];
    }

    /**
     * Sets videoPopupUrl
     *
     * @param string|mixed $videoPopupUrl videoPopupUrl
     *
     * @return $this
     */
    public function setVideoPopupUrl($videoPopupUrl)
    {
        $this->container['videoPopupUrl'] = $videoPopupUrl;

        return $this;
    }

    /**
     * Gets videoPopupButton
     *
     * @return \TencentAds\Model\AdcreativeVideoPopupButton|mixed
     */
    public function getVideoPopupButton()
    {
        return $this->container['videoPopupButton'];
    }

    /**
     * Sets videoPopupButton
     *
     * @param \TencentAds\Model\AdcreativeVideoPopupButton|mixed $videoPopupButton videoPopupButton
     *
     * @return $this
     */
    public function setVideoPopupButton($videoPopupButton)
    {
        $this->container['videoPopupButton'] = $videoPopupButton;

        return $this;
    }

    /**
     * Gets buttonUrl
     *
     * @return string|mixed
     */
    public function getButtonUrl()
    {
        return $this->container['buttonUrl'];
    }

    /**
     * Sets buttonUrl
     *
     * @param string|mixed $buttonUrl buttonUrl
     *
     * @return $this
     */
    public function setButtonUrl($buttonUrl)
    {
        $this->container['buttonUrl'] = $buttonUrl;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return \TencentAds\Model\AdCreativeBrand|mixed
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param \TencentAds\Model\AdCreativeBrand|mixed $brand brand
     *
     * @return $this
     */
    public function setBrand($brand)
    {
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets caption
     *
     * @return string|mixed
     */
    public function getCaption()
    {
        return $this->container['caption'];
    }

    /**
     * Sets caption
     *
     * @param string|mixed $caption caption
     *
     * @return $this
     */
    public function setCaption($caption)
    {
        $this->container['caption'] = $caption;

        return $this;
    }

    /**
     * Gets labelledImg
     *
     * @return \TencentAds\Model\AdcreativeLabelledImg|mixed
     */
    public function getLabelledImg()
    {
        return $this->container['labelledImg'];
    }

    /**
     * Sets labelledImg
     *
     * @param \TencentAds\Model\AdcreativeLabelledImg|mixed $labelledImg labelledImg
     *
     * @return $this
     */
    public function setLabelledImg($labelledImg)
    {
        $this->container['labelledImg'] = $labelledImg;

        return $this;
    }

    /**
     * Gets fullScreenImage
     *
     * @return string|mixed
     */
    public function getFullScreenImage()
    {
        return $this->container['fullScreenImage'];
    }

    /**
     * Sets fullScreenImage
     *
     * @param string|mixed $fullScreenImage fullScreenImage
     *
     * @return $this
     */
    public function setFullScreenImage($fullScreenImage)
    {
        $this->container['fullScreenImage'] = $fullScreenImage;

        return $this;
    }

    /**
     * Gets zipUrl
     *
     * @return string|mixed
     */
    public function getZipUrl()
    {
        return $this->container['zipUrl'];
    }

    /**
     * Sets zipUrl
     *
     * @param string|mixed $zipUrl zipUrl
     *
     * @return $this
     */
    public function setZipUrl($zipUrl)
    {
        $this->container['zipUrl'] = $zipUrl;

        return $this;
    }

    /**
     * Gets endPage
     *
     * @return \TencentAds\Model\AdCreativeEndPage|mixed
     */
    public function getEndPage()
    {
        return $this->container['endPage'];
    }

    /**
     * Sets endPage
     *
     * @param \TencentAds\Model\AdCreativeEndPage|mixed $endPage endPage
     *
     * @return $this
     */
    public function setEndPage($endPage)
    {
        $this->container['endPage'] = $endPage;

        return $this;
    }

    /**
     * Gets headLine
     *
     * @return string|mixed
     */
    public function getHeadLine()
    {
        return $this->container['headLine'];
    }

    /**
     * Sets headLine
     *
     * @param string|mixed $headLine headLine
     *
     * @return $this
     */
    public function setHeadLine($headLine)
    {
        $this->container['headLine'] = $headLine;

        return $this;
    }

    /**
     * Gets shopImageStruct
     *
     * @return \TencentAds\Model\AdCreativeShopImageStruct|mixed
     */
    public function getShopImageStruct()
    {
        return $this->container['shopImageStruct'];
    }

    /**
     * Sets shopImageStruct
     *
     * @param \TencentAds\Model\AdCreativeShopImageStruct|mixed $shopImageStruct shopImageStruct
     *
     * @return $this
     */
    public function setShopImageStruct($shopImageStruct)
    {
        $this->container['shopImageStruct'] = $shopImageStruct;

        return $this;
    }

    /**
     * Gets chosenButton
     *
     * @return \TencentAds\Model\ChosenButton|mixed
     */
    public function getChosenButton()
    {
        return $this->container['chosenButton'];
    }

    /**
     * Sets chosenButton
     *
     * @param \TencentAds\Model\ChosenButton|mixed $chosenButton chosenButton
     *
     * @return $this
     */
    public function setChosenButton($chosenButton)
    {
        $this->container['chosenButton'] = $chosenButton;

        return $this;
    }

    /**
     * Gets livingDescStruct
     *
     * @return \TencentAds\Model\AdCreativeLivingDescStruct|mixed
     */
    public function getLivingDescStruct()
    {
        return $this->container['livingDescStruct'];
    }

    /**
     * Sets livingDescStruct
     *
     * @param \TencentAds\Model\AdCreativeLivingDescStruct|mixed $livingDescStruct livingDescStruct
     *
     * @return $this
     */
    public function setLivingDescStruct($livingDescStruct)
    {
        $this->container['livingDescStruct'] = $livingDescStruct;

        return $this;
    }

    /**
     * Gets floatingZoneStruct
     *
     * @return \TencentAds\Model\FloatingZone|mixed
     */
    public function getFloatingZoneStruct()
    {
        return $this->container['floatingZoneStruct'];
    }

    /**
     * Sets floatingZoneStruct
     *
     * @param \TencentAds\Model\FloatingZone|mixed $floatingZoneStruct floatingZoneStruct
     *
     * @return $this
     */
    public function setFloatingZoneStruct($floatingZoneStruct)
    {
        $this->container['floatingZoneStruct'] = $floatingZoneStruct;

        return $this;
    }

    /**
     * Gets canvasShareImage
     *
     * @return string|mixed
     */
    public function getCanvasShareImage()
    {
        return $this->container['canvasShareImage'];
    }

    /**
     * Sets canvasShareImage
     *
     * @param string|mixed $canvasShareImage canvasShareImage
     *
     * @return $this
     */
    public function setCanvasShareImage($canvasShareImage)
    {
        $this->container['canvasShareImage'] = $canvasShareImage;

        return $this;
    }

    /**
     * Gets wegameInfoSpec
     *
     * @return \TencentAds\Model\WegameInfoSpec|mixed
     */
    public function getWegameInfoSpec()
    {
        return $this->container['wegameInfoSpec'];
    }

    /**
     * Sets wegameInfoSpec
     *
     * @param \TencentAds\Model\WegameInfoSpec|mixed $wegameInfoSpec wegameInfoSpec
     *
     * @return $this
     */
    public function setWegameInfoSpec($wegameInfoSpec)
    {
        $this->container['wegameInfoSpec'] = $wegameInfoSpec;

        return $this;
    }

    /**
     * Gets wechatChannelsSpec
     *
     * @return \TencentAds\Model\AdCreativeWechatChannelsSpec|mixed
     */
    public function getWechatChannelsSpec()
    {
        return $this->container['wechatChannelsSpec'];
    }

    /**
     * Sets wechatChannelsSpec
     *
     * @param \TencentAds\Model\AdCreativeWechatChannelsSpec|mixed $wechatChannelsSpec wechatChannelsSpec
     *
     * @return $this
     */
    public function setWechatChannelsSpec($wechatChannelsSpec)
    {
        $this->container['wechatChannelsSpec'] = $wechatChannelsSpec;

        return $this;
    }

    /**
     * Gets finderObjectVisibility
     *
     * @return bool|mixed
     */
    public function getFinderObjectVisibility()
    {
        return $this->container['finderObjectVisibility'];
    }

    /**
     * Sets finderObjectVisibility
     *
     * @param bool|mixed $finderObjectVisibility finderObjectVisibility
     *
     * @return $this
     */
    public function setFinderObjectVisibility($finderObjectVisibility)
    {
        $this->container['finderObjectVisibility'] = $finderObjectVisibility;

        return $this;
    }

    /**
     * Gets actionButtonComponentOptions
     *
     * @return \TencentAds\Model\ActionButtonComponentOption[]|mixed
     */
    public function getActionButtonComponentOptions()
    {
        return $this->container['actionButtonComponentOptions'];
    }

    /**
     * Sets actionButtonComponentOptions
     *
     * @param \TencentAds\Model\ActionButtonComponentOption[]|mixed $actionButtonComponentOptions actionButtonComponentOptions
     *
     * @return $this
     */
    public function setActionButtonComponentOptions($actionButtonComponentOptions)
    {
        $this->container['actionButtonComponentOptions'] = $actionButtonComponentOptions;

        return $this;
    }

    /**
     * Gets chosenButtonComponentOptions
     *
     * @return \TencentAds\Model\ChosenButtonComponentOption[]|mixed
     */
    public function getChosenButtonComponentOptions()
    {
        return $this->container['chosenButtonComponentOptions'];
    }

    /**
     * Sets chosenButtonComponentOptions
     *
     * @param \TencentAds\Model\ChosenButtonComponentOption[]|mixed $chosenButtonComponentOptions chosenButtonComponentOptions
     *
     * @return $this
     */
    public function setChosenButtonComponentOptions($chosenButtonComponentOptions)
    {
        $this->container['chosenButtonComponentOptions'] = $chosenButtonComponentOptions;

        return $this;
    }

    /**
     * Gets video2ComponentOptions
     *
     * @return \TencentAds\Model\VideoComponentOption[]|mixed
     */
    public function getVideo2ComponentOptions()
    {
        return $this->container['video2ComponentOptions'];
    }

    /**
     * Sets video2ComponentOptions
     *
     * @param \TencentAds\Model\VideoComponentOption[]|mixed $video2ComponentOptions video2ComponentOptions
     *
     * @return $this
     */
    public function setVideo2ComponentOptions($video2ComponentOptions)
    {
        $this->container['video2ComponentOptions'] = $video2ComponentOptions;

        return $this;
    }

    /**
     * Gets imageListJumpInfo
     *
     * @return \TencentAds\Model\LandingPageStructure[]|mixed
     */
    public function getImageListJumpInfo()
    {
        return $this->container['imageListJumpInfo'];
    }

    /**
     * Sets imageListJumpInfo
     *
     * @param \TencentAds\Model\LandingPageStructure[]|mixed $imageListJumpInfo imageListJumpInfo
     *
     * @return $this
     */
    public function setImageListJumpInfo($imageListJumpInfo)
    {
        $this->container['imageListJumpInfo'] = $imageListJumpInfo;

        return $this;
    }

    /**
     * Gets originVideo
     *
     * @return string|mixed
     */
    public function getOriginVideo()
    {
        return $this->container['originVideo'];
    }

    /**
     * Sets originVideo
     *
     * @param string|mixed $originVideo originVideo
     *
     * @return $this
     */
    public function setOriginVideo($originVideo)
    {
        $this->container['originVideo'] = $originVideo;

        return $this;
    }

    /**
     * Gets redEnvelopeStruct
     *
     * @return \TencentAds\Model\RedEnvelopeStruct|mixed
     */
    public function getRedEnvelopeStruct()
    {
        return $this->container['redEnvelopeStruct'];
    }

    /**
     * Sets redEnvelopeStruct
     *
     * @param \TencentAds\Model\RedEnvelopeStruct|mixed $redEnvelopeStruct redEnvelopeStruct
     *
     * @return $this
     */
    public function setRedEnvelopeStruct($redEnvelopeStruct)
    {
        $this->container['redEnvelopeStruct'] = $redEnvelopeStruct;

        return $this;
    }

    /**
     * Gets buttonTextJumpInfo
     *
     * @return \TencentAds\Model\LandingPageStructure|mixed
     */
    public function getButtonTextJumpInfo()
    {
        return $this->container['buttonTextJumpInfo'];
    }

    /**
     * Sets buttonTextJumpInfo
     *
     * @param \TencentAds\Model\LandingPageStructure|mixed $buttonTextJumpInfo buttonTextJumpInfo
     *
     * @return $this
     */
    public function setButtonTextJumpInfo($buttonTextJumpInfo)
    {
        $this->container['buttonTextJumpInfo'] = $buttonTextJumpInfo;

        return $this;
    }

    /**
     * Gets promotionSublinkComponentOptions
     *
     * @return \TencentAds\Model\PromotionSublinkComponentOption[]|mixed
     */
    public function getPromotionSublinkComponentOptions()
    {
        return $this->container['promotionSublinkComponentOptions'];
    }

    /**
     * Sets promotionSublinkComponentOptions
     *
     * @param \TencentAds\Model\PromotionSublinkComponentOption[]|mixed $promotionSublinkComponentOptions promotionSublinkComponentOptions
     *
     * @return $this
     */
    public function setPromotionSublinkComponentOptions($promotionSublinkComponentOptions)
    {
        $this->container['promotionSublinkComponentOptions'] = $promotionSublinkComponentOptions;

        return $this;
    }

    /**
     * Gets wxgamePlayablePageSpec
     *
     * @return \TencentAds\Model\WxgamePlayablePageSpec|mixed
     */
    public function getWxgamePlayablePageSpec()
    {
        return $this->container['wxgamePlayablePageSpec'];
    }

    /**
     * Sets wxgamePlayablePageSpec
     *
     * @param \TencentAds\Model\WxgamePlayablePageSpec|mixed $wxgamePlayablePageSpec wxgamePlayablePageSpec
     *
     * @return $this
     */
    public function setWxgamePlayablePageSpec($wxgamePlayablePageSpec)
    {
        $this->container['wxgamePlayablePageSpec'] = $wxgamePlayablePageSpec;

        return $this;
    }

    /**
     * Gets mainJumpInfo
     *
     * @return \TencentAds\Model\LandingPageStructure[]|mixed
     */
    public function getMainJumpInfo()
    {
        return $this->container['mainJumpInfo'];
    }

    /**
     * Sets mainJumpInfo
     *
     * @param \TencentAds\Model\LandingPageStructure[]|mixed $mainJumpInfo mainJumpInfo
     *
     * @return $this
     */
    public function setMainJumpInfo($mainJumpInfo)
    {
        $this->container['mainJumpInfo'] = $mainJumpInfo;

        return $this;
    }

    /**
     * Gets mdpaTitleComponentOptions
     *
     * @return \TencentAds\Model\MdpaTitleComponentOption[]|mixed
     */
    public function getMdpaTitleComponentOptions()
    {
        return $this->container['mdpaTitleComponentOptions'];
    }

    /**
     * Sets mdpaTitleComponentOptions
     *
     * @param \TencentAds\Model\MdpaTitleComponentOption[]|mixed $mdpaTitleComponentOptions mdpaTitleComponentOptions
     *
     * @return $this
     */
    public function setMdpaTitleComponentOptions($mdpaTitleComponentOptions)
    {
        $this->container['mdpaTitleComponentOptions'] = $mdpaTitleComponentOptions;

        return $this;
    }

    /**
     * Gets mdpaDescComponentOptions
     *
     * @return \TencentAds\Model\MdpaDescComponentOption[]|mixed
     */
    public function getMdpaDescComponentOptions()
    {
        return $this->container['mdpaDescComponentOptions'];
    }

    /**
     * Sets mdpaDescComponentOptions
     *
     * @param \TencentAds\Model\MdpaDescComponentOption[]|mixed $mdpaDescComponentOptions mdpaDescComponentOptions
     *
     * @return $this
     */
    public function setMdpaDescComponentOptions($mdpaDescComponentOptions)
    {
        $this->container['mdpaDescComponentOptions'] = $mdpaDescComponentOptions;

        return $this;
    }

    /**
     * Gets listSublinkComponentOptions
     *
     * @return \TencentAds\Model\ListSublinkComponentOption[]|mixed
     */
    public function getListSublinkComponentOptions()
    {
        return $this->container['listSublinkComponentOptions'];
    }

    /**
     * Sets listSublinkComponentOptions
     *
     * @param \TencentAds\Model\ListSublinkComponentOption[]|mixed $listSublinkComponentOptions listSublinkComponentOptions
     *
     * @return $this
     */
    public function setListSublinkComponentOptions($listSublinkComponentOptions)
    {
        $this->container['listSublinkComponentOptions'] = $listSublinkComponentOptions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


