<?php
/**
 * RoleType
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;
use \TencentAds\ObjectSerializer;

/**
 * RoleType Class Doc Comment
 *
 * @category Class
 * @description 角色
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoleType
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'ROLE_TYPE_UNKNOWN';
    const ADMIN = 'ROLE_TYPE_ADMIN';
    const OBSERVER = 'ROLE_TYPE_OBSERVER';
    const OPERATOR = 'ROLE_TYPE_OPERATOR';
    const TREASURER = 'ROLE_TYPE_TREASURER';
    const ASSISTANT = 'ROLE_TYPE_ASSISTANT';
    const SELF_OPERATOR = 'ROLE_TYPE_SELF_OPERATOR';
    const ROOT = 'ROLE_TYPE_ROOT';
    const AGENCY_BOSS = 'ROLE_TYPE_AGENCY_BOSS';
    const AGENCY_ADMIN = 'ROLE_TYPE_AGENCY_ADMIN';
    const AGENCY_OBSERVER = 'ROLE_TYPE_AGENCY_OBSERVER';
    const AGENCY_TREASURER = 'ROLE_TYPE_AGENCY_TREASURER';
    const AGENCY_OPERATOR = 'ROLE_TYPE_AGENCY_OPERATOR';
    const AGENCY_PROVIDER_OPERATOR = 'ROLE_TYPE_AGENCY_PROVIDER_OPERATOR';
    const AGENCY_PROVIDER_OBSERVER = 'ROLE_TYPE_AGENCY_PROVIDER_OBSERVER';
    const AGENCY_YYB = 'ROLE_TYPE_AGENCY_YYB';
    const AGENCY_AGENT_OPERATOR = 'ROLE_TYPE_AGENCY_AGENT_OPERATOR';
    const AGENCY_SELF_OPERATOR = 'ROLE_TYPE_AGENCY_SELF_OPERATOR';
    const AGENCY_MDM_BOSS = 'ROLE_TYPE_AGENCY_MDM_BOSS';
    const AGENCY_MDM_ADMIN = 'ROLE_TYPE_AGENCY_MDM_ADMIN';
    const AGENCY_MDM_TREASURER = 'ROLE_TYPE_AGENCY_MDM_TREASURER';
    const AGENCY_MDM_OBSERVER = 'ROLE_TYPE_AGENCY_MDM_OBSERVER';
    const AGENCY_MDM_OPERATOR = 'ROLE_TYPE_AGENCY_MDM_OPERATOR';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::ADMIN,
            self::OBSERVER,
            self::OPERATOR,
            self::TREASURER,
            self::ASSISTANT,
            self::SELF_OPERATOR,
            self::ROOT,
            self::AGENCY_BOSS,
            self::AGENCY_ADMIN,
            self::AGENCY_OBSERVER,
            self::AGENCY_TREASURER,
            self::AGENCY_OPERATOR,
            self::AGENCY_PROVIDER_OPERATOR,
            self::AGENCY_PROVIDER_OBSERVER,
            self::AGENCY_YYB,
            self::AGENCY_AGENT_OPERATOR,
            self::AGENCY_SELF_OPERATOR,
            self::AGENCY_MDM_BOSS,
            self::AGENCY_MDM_ADMIN,
            self::AGENCY_MDM_TREASURER,
            self::AGENCY_MDM_OBSERVER,
            self::AGENCY_MDM_OPERATOR,
        ];
    }
}


