<?php
/**
 * WechatAccountWechatFundType
 *
 * PHP version 5
 *
 * @category Class
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * Marketing API
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TencentAds\Model;
use \TencentAds\ObjectSerializer;

/**
 * WechatAccountWechatFundType Class Doc Comment
 *
 * @category Class
 * @description 资金类型
 * @package  TencentAds
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WechatAccountWechatFundType
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'UNKNOWN';
    const FUND_TYPE_UNSUPPPORTED = 'FUND_TYPE_UNSUPPPORTED';
    const FUND_TYPE_CASH = 'FUND_TYPE_CASH';
    const FUND_TYPE_GIFT = 'FUND_TYPE_GIFT';
    const FUND_TYPE_CREDIT_ROLL = 'FUND_TYPE_CREDIT_ROLL';
    const FUND_TYPE_CREDIT_TEMPORARY = 'FUND_TYPE_CREDIT_TEMPORARY';
    const FUND_TYPE_SPECIAL_PROMOTION = 'FUND_TYPE_SPECIAL_PROMOTION';
    const FUND_TYPE_CREDIT = 'FUND_TYPE_CREDIT';
    const FUND_TYPE_PAYMENT_DUE = 'FUND_TYPE_PAYMENT_DUE';
    const FUND_TYPE_MINIPROGRAM = 'FUND_TYPE_MINIPROGRAM';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::FUND_TYPE_UNSUPPPORTED,
            self::FUND_TYPE_CASH,
            self::FUND_TYPE_GIFT,
            self::FUND_TYPE_CREDIT_ROLL,
            self::FUND_TYPE_CREDIT_TEMPORARY,
            self::FUND_TYPE_SPECIAL_PROMOTION,
            self::FUND_TYPE_CREDIT,
            self::FUND_TYPE_PAYMENT_DUE,
            self::FUND_TYPE_MINIPROGRAM,
        ];
    }
}


